In [1]:
%pip install requests pandas openpyxl

Requirement already satisfied: requests in c:\Users\Samsung\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.34.2)
Requirement already satisfied: pandas in c:\Users\Samsung\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: openpyxl in c:\Users\Samsung\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.1.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\Samsung\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\Samsung\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\Samsung\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\Samsung\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests) (2026.6.17)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\Samsung\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Samsung\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Samsung\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: et-xmlfile in c:\Users\Samsung\AppData\Local\Programs\Python\Python314\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in C:\Users\Samsung\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import requests
import pandas as pd
from pathlib import Path

API_KEY = input("Pegá tu API key de API-Football: ").strip()

BASE_URL = "https://v3.football.api-sports.io"

HEADERS = {
    "x-apisports-key": API_KEY
}

LEAGUE_ID = 1
SEASON = 2026

PROJECT_DIR = Path.cwd().parent
OUTPUT_DIR = PROJECT_DIR / "Data" / "Processed"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("API key cargada correctamente.")
print("Carpeta de salida:", OUTPUT_DIR)

In [ ]:
import requests
import pandas as pd
from pathlib import Path

API_KEY = input("Pegá tu API key de API-Football: ").strip()

BASE_URL = "https://v3.football.api-sports.io"

HEADERS = {
    "x-apisports-key": API_KEY
}

LEAGUE_ID = 1
SEASON = 2026

PROJECT_DIR = Path.cwd().parent
OUTPUT_DIR = PROJECT_DIR / "Data" / "Processed"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("API key cargada correctamente.")
print("Carpeta de salida:", OUTPUT_DIR)

In [ ]:
import requests
import pandas as pd
from pathlib import Path

API_KEY = "xxxxxxxxxxxxxxxxxxxxxxxx"

BASE_URL = "https://v3.football.api-sports.io"

HEADERS = {
    "x-apisports-key": API_KEY
}

LEAGUE_ID = 1
SEASON = 2026

PROJECT_DIR = Path.cwd().parent
OUTPUT_DIR = PROJECT_DIR / "Data" / "Processed"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("API key cargada correctamente.")
print("Carpeta de salida:", OUTPUT_DIR)

In [ ]:
%pip install requests pandas openpyxl

In [1]:
print("hola")

hola

In [2]:
import requests
import pandas as pd
from pathlib import Path

API_KEY = "272ed9489a9dc972b509a174e40f7856"

BASE_URL = "https://v3.football.api-sports.io"

HEADERS = {
    "x-apisports-key": API_KEY
}

LEAGUE_ID = 1
SEASON = 2026

PROJECT_DIR = Path.cwd().parent
OUTPUT_DIR = PROJECT_DIR / "Data" / "Processed"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("API key cargada correctamente.")
print("Carpeta de salida:", OUTPUT_DIR)

API key cargada correctamente.
Carpeta de salida: c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Data\Processed

In [3]:
def api_get(endpoint, params=None):
    url = f"{BASE_URL}/{endpoint}"
    response = requests.get(url, headers=HEADERS, params=params, timeout=30)

    print("Status code:", response.status_code)

    if response.status_code != 200:
        print(response.text)
        raise Exception(f"Error {response.status_code}")

    data = response.json()

    if data.get("errors"):
        print("Errores API:", data["errors"])

    return data

test = api_get("status")

test

Status code: 200

{'get': 'status',
 'parameters': [],
 'errors': [],
 'results': 0,
 'paging': {'current': 1, 'total': 1},
 'response': {'account': {'firstname': 'Ivan',
   'lastname': 'Alderete',
   'email': 'ivanalderete10@gmail.com'},
  'subscription': {'plan': 'Free',
   'end': '2027-06-28T00:00:00+00:00',
   'active': True},
  'requests': {'current': 0, 'limit_day': 100}}}

In [4]:
teams_data = api_get(
    "teams",
    {
        "league": LEAGUE_ID,
        "season": SEASON
    }
)

teams_rows = []

for item in teams_data["response"]:
    team = item["team"]
    venue = item.get("venue", {})
    
    teams_rows.append({
        "api_team_id": team.get("id"),
        "team": team.get("name"),
        "team_code": team.get("code"),
        "country": team.get("country"),
        "national": team.get("national"),
        "team_logo": team.get("logo"),
        "venue_id": venue.get("id"),
        "venue_name": venue.get("name"),
        "venue_city": venue.get("city")
    })

api_teams = pd.DataFrame(teams_rows)

api_teams.to_excel(OUTPUT_DIR / "api_worldcup_teams.xlsx", index=False)

print("Equipos descargados:", len(api_teams))
display(api_teams)

Status code: 200
Errores API: {'plan': 'Free plans do not have access to this season, try from 2022 to 2024.'}
Equipos descargados: 0

Empty DataFrame
Columns: []
Index: []

In [5]:
teams_data = api_get(
    "teams",
    {
        "league": LEAGUE_ID,
        "season": SEASON
    }
)

teams_rows = []

for item in teams_data["response"]:
    team = item["team"]
    venue = item.get("venue", {})
    
    teams_rows.append({
        "api_team_id": team.get("id"),
        "team": team.get("name"),
        "team_code": team.get("code"),
        "country": team.get("country"),
        "national": team.get("national"),
        "team_logo": team.get("logo"),
        "venue_id": venue.get("id"),
        "venue_name": venue.get("name"),
        "venue_city": venue.get("city")
    })

api_teams = pd.DataFrame(teams_rows)

api_teams.to_excel(OUTPUT_DIR / "api_worldcup_teams.xlsx", index=False)

print("Equipos descargados:", len(api_teams))
display(api_teams)

Status code: 200
Errores API: {'plan': 'Free plans do not have access to this season, try from 2022 to 2024.'}
Equipos descargados: 0

Empty DataFrame
Columns: []
Index: []

In [6]:
import requests
import pandas as pd
from pathlib import Path

OPEN_BASE_URL = "https://worldcup26.ir"

PROJECT_DIR = Path.cwd().parent
OUTPUT_DIR = PROJECT_DIR / "Data" / "Processed"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("Usando API gratuita WorldCup26")
print("Carpeta de salida:", OUTPUT_DIR)

Usando API gratuita WorldCup26
Carpeta de salida: c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Data\Processed

In [7]:
def open_api_get(endpoint):
    url = f"{OPEN_BASE_URL}{endpoint}"
    
    response = requests.get(url, timeout=30)
    
    print("Endpoint:", endpoint)
    print("Status code:", response.status_code)
    
    if response.status_code != 200:
        print(response.text)
        raise Exception(f"Error {response.status_code}")
    
    return response.json()


def unwrap_api_response(data):
    """
    Esta función intenta encontrar la lista principal dentro de la respuesta,
    aunque la API cambie un poco el nombre del campo.
    """
    
    if isinstance(data, list):
        return data
    
    if isinstance(data, dict):
        possible_keys = [
            "data",
            "response",
            "teams",
            "games",
            "matches",
            "groups",
            "stadiums",
            "result"
        ]
        
        for key in possible_keys:
            if key in data:
                return data[key]
    
    return data

In [8]:
teams_json = open_api_get("/get/teams")
teams_data = unwrap_api_response(teams_json)

api_teams_open = pd.json_normalize(teams_data)

api_teams_open.to_excel(
    OUTPUT_DIR / "open_worldcup_teams.xlsx",
    index=False
)

print("Equipos descargados:", len(api_teams_open))
display(api_teams_open.head(50))
print(api_teams_open.columns.tolist())

Endpoint: /get/teams
Status code: 200
Equipos descargados: 48

,_id,name_en,name_fa,flag,fifa_code,iso2,groups,id
0,679c9c6b5749c4077500ea01,Mexico,مکزیک,https://flagcdn.com/w80/mx.png,MEX,MX,A,1
1,679c9c6b5749c4077500ea02,South Africa,آفریقای جنوبی,https://flagcdn.com/w80/za.png,RSA,ZA,A,2
2,679c9c6b5749c4077500ea03,South Korea,کره جنوبی,https://flagcdn.com/w80/kr.png,KOR,KR,A,3
3,679c9c6b5749c4077500ea04,Czech Republic,جمهوری چک,https://flagcdn.com/w80/cz.png,CZE,CZ,A,4
4,679c9c6b5749c4077500ea05,Canada,کانادا,https://flagcdn.com/w80/ca.png,CAN,CA,B,5
5,679c9c6b5749c4077500ea06,Bosnia and Herzegovina,بوسنی و هرزگوین,https://flagcdn.com/w80/ba.png,BIH,BA,B,6
6,679c9c6b5749c4077500ea07,Qatar,قطر,https://flagcdn.com/w80/qa.png,QAT,QA,B,7
7,679c9c6b5749c4077500ea08,Switzerland,سوئیس,https://flagcdn.com/w80/ch.png,SUI,CH,B,8
8,679c9c6b5749c4077500ea09,Brazil,برزیل,https://flagcdn.com/w80/br.png,BRA,BR,C,9
9,679c9c6b5749c4077500ea10,Morocco,مراکش,https://flagcdn.com/w80/ma.png,MAR,MA,C,10
10,679c9c6b5749c4077500ea11,Haiti,هائیتی,https://flagcdn.com/w80/ht.png,HAI,HT,C,11
11,679c9c6b5749c4077500ea12,Scotland,اسکاتلند,https://flagcdn.com/w80/gb-sct.png,SCO,SCO,C,12
12,679c9c6b5749c4077500ea13,United States,آمریکا,https://flagcdn.com/w80/us.png,USA,US,D,13
13,679c9c6b5749c4077500ea14,Paraguay,پاراگوئه,https://flagcdn.com/w80/py.png,PAR,PY,D,14
14,679c9c6b5749c4077500ea15,Australia,استرالیا,https://flagcdn.com/w80/au.png,AUS,AU,D,15
15,679c9c6b5749c4077500ea16,Turkey,ترکیه,https://flagcdn.com/w80/tr.png,TUR,TR,D,16
16,679c9c6b5749c4077500ea17,Germany,آلمان,https://flagcdn.com/w80/de.png,GER,DE,E,17
17,679c9c6b5749c4077500ea18,Curaçao,کوراسائو,https://flagcdn.com/w80/cw.png,CUW,CW,E,18
18,679c9c6b5749c4077500ea19,Ivory Coast,ساحل عاج,https://flagcdn.com/w80/ci.png,CIV,CI,E,19
19,679c9c6b5749c4077500ea20,Ecuador,اکوادور,https://flagcdn.com/w80/ec.png,ECU,EC,E,20
20,679c9c6b5749c4077500ea21,Netherlands,هلند,https://flagcdn.com/w80/nl.png,NED,NL,F,21
21,679c9c6b5749c4077500ea22,Japan,ژاپن,https://flagcdn.com/w80/jp.png,JPN,JP,F,22
22,679c9c6b5749c4077500ea23,Sweden,سوئد,https://flagcdn.com/w80/se.png,SWE,SE,F,23
23,679c9c6b5749c4077500ea24,Tunisia,تونس,https://flagcdn.com/w80/tn.png,TUN,TN,F,24
24,679c9c6b5749c4077500ea25,Belgium,بلژیک,https://flagcdn.com/w80/be.png,BEL,BE,G,25
25,679c9c6b5749c4077500ea26,Egypt,مصر,https://flagcdn.com/w80/eg.png,EGY,EG,G,26
26,679c9c6b5749c4077500ea27,Iran,ایران,https://flagcdn.com/w80/ir.png,IRN,IR,G,27
27,679c9c6b5749c4077500ea28,New Zealand,نیوزیلند,https://flagcdn.com/w80/nz.png,NZL,NZ,G,28
28,679c9c6b5749c4077500ea29,Spain,اسپانیا,https://flagcdn.com/w80/es.png,ESP,ES,H,29
29,679c9c6b5749c4077500ea30,Cape Verde,کیپ ورد,https://flagcdn.com/w80/cv.png,CPV,CV,H,30
30,679c9c6b5749c4077500ea31,Saudi Arabia,عربستان,https://flagcdn.com/w80/sa.png,KSA,SA,H,31
31,679c9c6b5749c4077500ea32,Uruguay,اروگوئه,https://flagcdn.com/w80/uy.png,URU,UY,H,32
32,679c9c6b5749c4077500ea33,France,فرانسه,https://flagcdn.com/w80/fr.png,FRA,FR,I,33
33,679c9c6b5749c4077500ea34,Senegal,سنگال,https://flagcdn.com/w80/sn.png,SEN,SN,I,34
34,679c9c6b5749c4077500ea35,Iraq,عراق,https://flagcdn.com/w80/iq.png,IRQ,IQ,I,35
35,679c9c6b5749c4077500ea36,Norway,نروژ,https://flagcdn.com/w80/no.png,NOR,NO,I,36
36,679c9c6b5749c4077500ea37,Argentina,آرژانتین,https://flagcdn.com/w80/ar.png,ARG,AR,J,37
37,679c9c6b5749c4077500ea38,Algeria,الجزایر,https://flagcdn.com/w80/dz.png,ALG,DZ,J,38
38,679c9c6b5749c4077500ea39,Austria,اتریش,https://flagcdn.com/w80/at.png,AUT,AT,J,39
39,679c9c6b5749c4077500ea40,Jordan,اردن,https://flagcdn.com/w80/jo.png,JOR,JO,J,40
40,679c9c6b5749c4077500ea41,Portugal,پرتغال,https://flagcdn.com/w80/pt.png,POR,PT,K,41
41,679c9c6b5749c4077500ea42,Democratic Republic of the Congo,جمهوری دموکراتیک کنگو,https://flagcdn.com/w80/cd.png,COD,CD,K,42
42,679c9c6b5749c4077500ea43,Uzbekistan,ازبکستان,https://flagcdn.com/w80/uz.png,UZB,UZ,K,43
43,679c9c6b5749c4077500ea44,Colombia,کلمبیا,https://flagcdn.com/w80/co.png,COL,CO,K,44
44,679c9c6b5749c4077500ea45,England,انگلستان,https://flagcdn.com/w80/gb-eng.png,ENG,ENG,L,45
45,679c9c6b5749c4077500ea46,Croatia,کرواسی,https://flagcdn.com/w80/hr.png,CRO,HR,L,46
46,679c9c6b5749c4077500ea47,Ghana,غنا,https://flagcdn.com/w80/gh.png,GHA,GH,L,47
47,679c9c6b5749c4077500ea48,Panama,پاناما,https://flagcdn.com/w80/pa.png,PAN,PA,L,48

['_id', 'name_en', 'name_fa', 'flag', 'fifa_code', 'iso2', 'groups', 'id']

In [9]:
games_json = open_api_get("/get/games")
games_data = unwrap_api_response(games_json)

api_games_open = pd.json_normalize(games_data)

api_games_open.to_excel(
    OUTPUT_DIR / "open_worldcup_games.xlsx",
    index=False
)

print("Partidos descargados:", len(api_games_open))
display(api_games_open.head(30))
print(api_games_open.columns.tolist())

Endpoint: /get/games
Status code: 200
Partidos descargados: 104

,_id,id,home_team_id,away_team_id,home_score,away_score,home_scorers,away_scorers,group,matchday,...,stadium_id,finished,time_elapsed,type,home_team_name_en,home_team_name_fa,away_team_name_en,away_team_name_fa,home_team_label,away_team_label
0,679c9c8a5749c4077500e006,6,15,16,2,0,"{""Nestory Irankunda 27'"",""C. Metcalfe 75'""}",null,D,1,...,13,TRUE,finished,group,Australia,استرالیا,Turkey,ترکیه,NaN,NaN
1,679c9c8a5749c4077500e008,8,7,8,1,1,"{""B. Khoukhi 90'+5'""}","{""Breel Embolo 17' (p)""}",B,1,...,15,TRUE,finished,group,Qatar,قطر,Switzerland,سوئیس,NaN,NaN
2,679c9c8a5749c4077500e031,31,13,15,2,0,"{""Kamrvn Bargs 11'"",""Alex Freeman 43'""}",null,D,2,...,14,TRUE,finished,group,United States,آمریکا,Australia,استرالیا,NaN,NaN
3,679c9c8a5749c4077500e033,33,17,19,2,1,"{""Dniz Avndav 68'"",""Dniz Avndav 90+4'""}","{""Franck Kessié 30'""}",E,2,...,12,TRUE,finished,group,Germany,آلمان,Ivory Coast,ساحل عاج,NaN,NaN
4,679c9c8a5749c4077500e035,35,21,23,5,1,"{""Brian Brobbey 5'"",""Brian Brobbey 17'"",""Kvdi ...","{""Anthony Elanga 59'""}",F,2,...,5,TRUE,finished,group,Netherlands,هلند,Sweden,سوئد,NaN,NaN
5,679c9c8a5749c4077500e041,41,33,35,3,0,"{""Kylian Mbappé 14'"",""Kylian Mbappé 54'"",""Ousm...",null,I,2,...,10,TRUE,finished,group,France,فرانسه,Iraq,عراق,NaN,NaN
6,679c9c8a5749c4077500e042,42,36,34,3,2,"{""Markvs Hlmgrn Pdrsn 43'"",""Erling Haaland 48'...","{""Ismaïla Sarr 53'"",""Ismaïla Sarr 90+3'""}",I,2,...,11,TRUE,finished,group,Norway,نروژ,Senegal,سنگال,NaN,NaN
7,679c9c8a5749c4077500e059,59,22,23,1,1,"{""Daizen Maeda 56'""}","{""Anthony Elanga 62'""}",F,3,...,4,TRUE,finished,group,Japan,ژاپن,Sweden,سوئد,NaN,NaN
8,679c9c8a5749c4077500e089,95,0,0,0,0,null,null,R16,5,...,7,FALSE,notstarted,r16,NaN,NaN,NaN,NaN,Winner Match 86,Winner Match 88
9,679c9c8a5749c4077500e08f,101,0,0,0,0,null,null,SF,7,...,4,FALSE,notstarted,sf,NaN,NaN,NaN,NaN,Winner Match 97,Winner Match 98
10,679c9c8a5749c4077500e090,102,0,0,0,0,null,null,SF,7,...,7,FALSE,notstarted,sf,NaN,NaN,NaN,NaN,Winner Match 99,Winner Match 100
11,679c9c8a5749c4077500e005,5,11,12,0,1,null,"{""J. McGinn 28'""}",C,1,...,9,TRUE,finished,group,Haiti,هائیتی,Scotland,اسکاتلند,NaN,NaN
12,679c9c8a5749c4077500e022,22,45,46,4,2,"{""H. Kane 12'(p)"",""H. Kane 42'"",""J. Bellingham...","{""M. Baturina 36'"",""P. Musa 45+5'""}",L,1,...,4,TRUE,finished,group,England,انگلستان,Croatia,کرواسی,NaN,NaN
13,679c9c8a5749c4077500e039,39,29,31,4,0,"{""Lamine Yamal 10'"",""Mikel Oyarzabal 21'"",""Mik...",null,H,2,...,7,TRUE,finished,group,Spain,اسپانیا,Saudi Arabia,عربستان,NaN,NaN
14,679c9c8a5749c4077500e044,44,40,38,1,2,"{""Al Rashdan 36'""}","{""Nzir Bnbvali 69'"",""Amine Gouiri 82'""}",J,2,...,15,TRUE,finished,group,Jordan,اردن,Algeria,الجزایر,NaN,NaN
15,679c9c8a5749c4077500e045,45,41,43,5,0,"{""Cristiano Ronaldo 6'"",""Nvnv Mndz 17'"",""Crist...",null,K,2,...,5,TRUE,finished,group,Portugal,پرتغال,Uzbekistan,ازبکستان,NaN,NaN
16,679c9c8a5749c4077500e046,46,48,46,0,1,null,"{""Ante Budimir 54'""}",L,2,...,12,TRUE,finished,group,Panama,پاناما,Croatia,کرواسی,NaN,NaN
17,679c9c8a5749c4077500e052,52,4,1,0,3,null,"{""Mateo Chávez 55'"",""Jvlian Kviinvnz 61'"",""Álv...",A,3,...,1,TRUE,finished,group,Czech Republic,جمهوری چک,Mexico,مکزیک,NaN,NaN
18,679c9c8a5749c4077500e060,60,24,21,1,3,"{""Hazm Mstvri 54'""}","{""Alis Skhiri 3'"",""Brian Brobbey 7'"",""Ian Fn H...",F,3,...,6,TRUE,finished,group,Tunisia,تونس,Netherlands,هلند,NaN,NaN
19,679c9c8a5749c4077500e061,61,34,35,5,0,"{""Habib Diarra 4'"",""Ismaïla Sarr 56'"",""Paph Gv...",null,I,3,...,12,TRUE,finished,group,Senegal,سنگال,Iraq,عراق,NaN,NaN
20,679c9c8a5749c4077500e067,67,48,45,0,2,null,"{""Jvd Blingham 62'"",""Hri Kin 67'""}",L,3,...,11,TRUE,finished,group,Panama,پاناما,England,انگلستان,NaN,NaN
21,679c9c8a5749c4077500e072,72,42,43,3,1,"{""Fistvn Mail 78'"",""Yoane Wissa 90+1'""}","{""Aldvr Shvmvrvdvf 10'""}",K,3,...,7,TRUE,finished,group,Democratic Republic of the Congo,جمهوری دموکراتیک کنگو,Uzbekistan,ازبکستان,NaN,NaN
22,679c9c8a5749c4077500e080,86,37,30,0,0,null,null,R32,4,...,8,FALSE,notstarted,r32,Argentina,آرژانتین,Cape Verde,کیپ ورد,Winner Group J,Runner-up Group H
23,679c9c8a5749c4077500e082,88,15,26,0,0,null,null,R32,4,...,4,FALSE,notstarted,r32,Australia,استرالیا,Egypt,مصر,Runner-up Group D,Runner-up Group G
24,679c9c8a5749c4077500e08e,100,0,0,0,0,null,null,QF,6,...,6,FALSE,notstarted,qf,NaN,NaN,NaN,NaN,Winner Match 95,Winner Match 96
25,679c9c8a5749c4077500e002,2,3,4,2,1,"{""I.B. Hwang 67'"",""H.G. Oh 80'""}","{""L. Krejčí 59'""}",A,1,...,2,TRUE,finished,group,South Korea,کره جنوبی,Czech Republic,جمهوری چک,NaN,NaN
26,679c9c8a5749c4077500e004,4,13,14,4,1,"{""D. Bobadilla 7'(OG)"",""F. Balogun 31'"",""F. Ba...","{""Maurício 73'""}",D,1,...,16,TRUE,finished,group,United States,آمریکا,Paraguay,پاراگوئه,NaN,NaN
27,679c9c8a5749c4077500e017,17,33,34,3,1,"{""K. Mbappé 66'"",""B. Barcola 82'"",""K. Mbappé 9...","{""I. Mbaye 90+5'""}",I,1,...,11,TRUE,finished,group,France,فرانسه,Senegal,سنگال,NaN,NaN
28,679c9c8a5749c4077500e018,18,35,36,1,4,"{""Aymen Hussein 39'""}","{""Erling Haaland 29'"",""Erling Haaland 43'"",""Le...",I,1,...,9,TRUE,finished,group,Iraq,عراق,Norway,نروژ,NaN,NaN
29,679c9c8a5749c4077500e021,21,41,42,1,1,"{""J. Neves 6'""}","{""Y. Wissa 45+5'""}",K,1,...,5,TRUE,Finished,group,Portugal,پرتغال,Democratic Republic of the Congo,جمهوری دموکراتیک کنگو,NaN,NaN

['_id', 'id', 'home_team_id', 'away_team_id', 'home_score', 'away_score', 'home_scorers', 'away_scorers', 'group', 'matchday', 'local_date', 'persian_date', 'stadium_id', 'finished', 'time_elapsed', 'type', 'home_team_name_en', 'home_team_name_fa', 'away_team_name_en', 'away_team_name_fa', 'home_team_label', 'away_team_label']

In [10]:
groups_json = open_api_get("/get/groups")
groups_data = unwrap_api_response(groups_json)

api_groups_open = pd.json_normalize(groups_data)

api_groups_open.to_excel(
    OUTPUT_DIR / "open_worldcup_groups.xlsx",
    index=False
)

print("Grupos descargados:", len(api_groups_open))
display(api_groups_open.head(20))
print(api_groups_open.columns.tolist())

Endpoint: /get/groups
Status code: 200
Grupos descargados: 12

,_id,name,teams,createdAt,__v,updatedAt
0,698985a46e8cb0bf61b5ac74,A,"[{'team_id': '1', 'mp': '3', 'w': '3', 'l': '0...",2026-02-09T06:58:44.331Z,0,2026-06-25T02:59:29.906Z
1,698985a46e8cb0bf61b5ac7a,B,"[{'team_id': '8', 'mp': '3', 'w': '2', 'l': '0...",2026-02-09T06:58:44.354Z,0,2026-06-24T20:59:32.129Z
2,698985a46e8cb0bf61b5ac80,C,"[{'team_id': '9', 'mp': '3', 'w': '2', 'l': '0...",2026-02-09T06:58:44.360Z,0,2026-06-25T00:03:07.897Z
3,698985a46e8cb0bf61b5ac86,D,"[{'team_id': '13', 'mp': '3', 'w': '2', 'l': '...",2026-02-09T06:58:44.364Z,0,2026-06-26T04:03:56.726Z
4,698985a46e8cb0bf61b5ac8c,E,"[{'team_id': '17', 'mp': '3', 'w': '2', 'l': '...",2026-02-09T06:58:44.367Z,0,2026-06-25T21:59:55.741Z
5,698985a46e8cb0bf61b5ac92,F,"[{'team_id': '21', 'mp': '3', 'w': '2', 'l': '...",2026-02-09T06:58:44.371Z,0,2026-06-26T00:59:38.629Z
6,698985a46e8cb0bf61b5ac98,G,"[{'team_id': '25', 'mp': '3', 'w': '1', 'l': '...",2026-02-09T06:58:44.374Z,0,2026-06-27T05:05:01.320Z
7,698985a46e8cb0bf61b5ac9e,H,"[{'team_id': '29', 'mp': '3', 'w': '2', 'l': '...",2026-02-09T06:58:44.378Z,0,2026-06-27T02:02:41.121Z
8,698985a46e8cb0bf61b5aca4,I,"[{'team_id': '33', 'mp': '3', 'w': '3', 'l': '...",2026-02-09T06:58:44.383Z,0,2026-06-26T21:05:33.086Z
9,698985a46e8cb0bf61b5acaa,J,"[{'team_id': '37', 'mp': '3', 'w': '3', 'l': '...",2026-02-09T06:58:44.388Z,0,2026-06-28T04:00:22.455Z
10,698985a46e8cb0bf61b5acb0,K,"[{'team_id': '44', 'mp': '3', 'w': '2', 'l': '...",2026-02-09T06:58:44.392Z,0,2026-06-28T01:33:01.267Z
11,698985a46e8cb0bf61b5acb6,L,"[{'team_id': '45', 'mp': '3', 'w': '2', 'l': '...",2026-02-09T06:58:44.396Z,0,2026-06-27T23:00:23.529Z

['_id', 'name', 'teams', 'createdAt', '__v', 'updatedAt']

In [11]:
stadiums_json = open_api_get("/get/stadiums")
stadiums_data = unwrap_api_response(stadiums_json)

api_stadiums_open = pd.json_normalize(stadiums_data)

api_stadiums_open.to_excel(
    OUTPUT_DIR / "open_worldcup_stadiums.xlsx",
    index=False
)

print("Estadios descargados:", len(api_stadiums_open))
display(api_stadiums_open.head(20))
print(api_stadiums_open.columns.tolist())

Endpoint: /get/stadiums
Status code: 200
Estadios descargados: 16

,_id,id,name_en,name_fa,fifa_name,city_en,city_fa,country_en,country_fa,capacity,region
0,679c9c8a5749c4077500f001,1,Estadio Azteca,استادیوم آزتکا,Mexico City Stadium,Mexico City,مکزیکوسیتی,Mexico,مکزیک,83000,Central
1,679c9c8a5749c4077500f002,2,Estadio Akron,استادیوم آکرون,Estadio Guadalajara,Guadalajara (Zapopan),گوادالاخارا,Mexico,مکزیک,48000,Central
2,679c9c8a5749c4077500f003,3,Estadio BBVA,استادیوم بی‌بی‌وی‌ای,Estadio Monterrey,Monterrey (Guadalupe),مونتری,Mexico,مکزیک,53500,Central
3,679c9c8a5749c4077500f004,4,AT&T Stadium,استادیوم ای‌تی‌اند‌تی,Dallas Stadium,"Dallas (Arlington, Texas)",دالاس,United States,آمریکا,94000,Central
4,679c9c8a5749c4077500f005,5,NRG Stadium,استادیوم ان‌آر‌جی,Houston Stadium,Houston,هیوستون,United States,آمریکا,72000,Central
5,679c9c8a5749c4077500f006,6,GEHA Field at Arrowhead Stadium,استادیوم اروهد,Kansas City Stadium,Kansas City,کانزاس سیتی,United States,آمریکا,73000,Central
6,679c9c8a5749c4077500f007,7,Mercedes-Benz Stadium,استادیوم مرسدس بنز,Atlanta Stadium,Atlanta,آتلانتا,United States,آمریکا,75000,Eastern
7,679c9c8a5749c4077500f008,8,Hard Rock Stadium,استادیوم هارد راک,Miami Stadium,Miami (Miami Gardens),میامی,United States,آمریکا,65000,Eastern
8,679c9c8a5749c4077500f009,9,Gillette Stadium,استادیوم ژیلت,Boston Stadium,Boston (Foxborough),بوستون,United States,آمریکا,65000,Eastern
9,679c9c8a5749c4077500f010,10,Lincoln Financial Field,استادیوم لینکلن فایننشال,Philadelphia Stadium,Philadelphia,فیلادلفیا,United States,آمریکا,69000,Eastern
10,679c9c8a5749c4077500f011,11,MetLife Stadium,استادیوم متلایف,New York/New Jersey Stadium,New York/New Jersey (East Rutherford),نیویورک/نیوجرسی,United States,آمریکا,82500,Eastern
11,679c9c8a5749c4077500f012,12,BMO Field,استادیوم بی‌ام‌او,Toronto Stadium,Toronto,تورنتو,Canada,کانادا,45000,Eastern
12,679c9c8a5749c4077500f013,13,BC Place,استادیوم بی‌سی پلیس,BC Place Vancouver,Vancouver,ونکوور,Canada,کانادا,54000,Western
13,679c9c8a5749c4077500f014,14,Lumen Field,استادیوم لومن فیلد,Seattle Stadium,Seattle,سیاتل,United States,آمریکا,69000,Western
14,679c9c8a5749c4077500f015,15,Levi's Stadium,استادیوم لیوایز,San Francisco Bay Area Stadium,San Francisco Bay Area (Santa Clara),سن‌فرانسیسکو,United States,آمریکا,71000,Western
15,679c9c8a5749c4077500f016,16,SoFi Stadium,استادیوم سوفای,Los Angeles Stadium,Los Angeles (Inglewood),لس‌آنجلس,United States,آمریکا,70000,Western

['_id', 'id', 'name_en', 'name_fa', 'fifa_name', 'city_en', 'city_fa', 'country_en', 'country_fa', 'capacity', 'region']

In [12]:
output_file = OUTPUT_DIR / "worldcup_open_live_data.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
    api_teams_open.to_excel(writer, sheet_name="teams", index=False)
    api_games_open.to_excel(writer, sheet_name="games", index=False)
    api_groups_open.to_excel(writer, sheet_name="groups", index=False)
    api_stadiums_open.to_excel(writer, sheet_name="stadiums", index=False)

print("Archivo creado correctamente:")
print(output_file)

Archivo creado correctamente:
c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Data\Processed\worldcup_open_live_data.xlsx

In [13]:
from pathlib import Path
import pandas as pd

live_file = OUTPUT_DIR / "worldcup_open_live_data.xlsx"

print("Archivo:", live_file)

sheets = pd.read_excel(live_file, sheet_name=None)

for sheet_name, df in sheets.items():
    print("\n" + "="*80)
    print("HOJA:", sheet_name)
    print("Filas:", len(df))
    print("Columnas:", len(df.columns))
    print(df.columns.tolist())
    display(df.head(10))

Archivo: c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Data\Processed\worldcup_open_live_data.xlsx

================================================================================
HOJA: teams
Filas: 48
Columnas: 8
['_id', 'name_en', 'name_fa', 'flag', 'fifa_code', 'iso2', 'groups', 'id']

,_id,name_en,name_fa,flag,fifa_code,iso2,groups,id
0,679c9c6b5749c4077500ea01,Mexico,مکزیک,https://flagcdn.com/w80/mx.png,MEX,MX,A,1
1,679c9c6b5749c4077500ea02,South Africa,آفریقای جنوبی,https://flagcdn.com/w80/za.png,RSA,ZA,A,2
2,679c9c6b5749c4077500ea03,South Korea,کره جنوبی,https://flagcdn.com/w80/kr.png,KOR,KR,A,3
3,679c9c6b5749c4077500ea04,Czech Republic,جمهوری چک,https://flagcdn.com/w80/cz.png,CZE,CZ,A,4
4,679c9c6b5749c4077500ea05,Canada,کانادا,https://flagcdn.com/w80/ca.png,CAN,CA,B,5
5,679c9c6b5749c4077500ea06,Bosnia and Herzegovina,بوسنی و هرزگوین,https://flagcdn.com/w80/ba.png,BIH,BA,B,6
6,679c9c6b5749c4077500ea07,Qatar,قطر,https://flagcdn.com/w80/qa.png,QAT,QA,B,7
7,679c9c6b5749c4077500ea08,Switzerland,سوئیس,https://flagcdn.com/w80/ch.png,SUI,CH,B,8
8,679c9c6b5749c4077500ea09,Brazil,برزیل,https://flagcdn.com/w80/br.png,BRA,BR,C,9
9,679c9c6b5749c4077500ea10,Morocco,مراکش,https://flagcdn.com/w80/ma.png,MAR,MA,C,10

================================================================================
HOJA: games
Filas: 104
Columnas: 22
['_id', 'id', 'home_team_id', 'away_team_id', 'home_score', 'away_score', 'home_scorers', 'away_scorers', 'group', 'matchday', 'local_date', 'persian_date', 'stadium_id', 'finished', 'time_elapsed', 'type', 'home_team_name_en', 'home_team_name_fa', 'away_team_name_en', 'away_team_name_fa', 'home_team_label', 'away_team_label']

,_id,id,home_team_id,away_team_id,home_score,away_score,home_scorers,away_scorers,group,matchday,...,stadium_id,finished,time_elapsed,type,home_team_name_en,home_team_name_fa,away_team_name_en,away_team_name_fa,home_team_label,away_team_label
0,679c9c8a5749c4077500e006,6,15,16,2,0,"{""Nestory Irankunda 27'"",""C. Metcalfe 75'""}",NaN,D,1,...,13,True,finished,group,Australia,استرالیا,Turkey,ترکیه,NaN,NaN
1,679c9c8a5749c4077500e008,8,7,8,1,1,"{""B. Khoukhi 90'+5'""}","{""Breel Embolo 17' (p)""}",B,1,...,15,True,finished,group,Qatar,قطر,Switzerland,سوئیس,NaN,NaN
2,679c9c8a5749c4077500e031,31,13,15,2,0,"{""Kamrvn Bargs 11'"",""Alex Freeman 43'""}",NaN,D,2,...,14,True,finished,group,United States,آمریکا,Australia,استرالیا,NaN,NaN
3,679c9c8a5749c4077500e033,33,17,19,2,1,"{""Dniz Avndav 68'"",""Dniz Avndav 90+4'""}","{""Franck Kessié 30'""}",E,2,...,12,True,finished,group,Germany,آلمان,Ivory Coast,ساحل عاج,NaN,NaN
4,679c9c8a5749c4077500e035,35,21,23,5,1,"{""Brian Brobbey 5'"",""Brian Brobbey 17'"",""Kvdi ...","{""Anthony Elanga 59'""}",F,2,...,5,True,finished,group,Netherlands,هلند,Sweden,سوئد,NaN,NaN
5,679c9c8a5749c4077500e041,41,33,35,3,0,"{""Kylian Mbappé 14'"",""Kylian Mbappé 54'"",""Ousm...",NaN,I,2,...,10,True,finished,group,France,فرانسه,Iraq,عراق,NaN,NaN
6,679c9c8a5749c4077500e042,42,36,34,3,2,"{""Markvs Hlmgrn Pdrsn 43'"",""Erling Haaland 48'...","{""Ismaïla Sarr 53'"",""Ismaïla Sarr 90+3'""}",I,2,...,11,True,finished,group,Norway,نروژ,Senegal,سنگال,NaN,NaN
7,679c9c8a5749c4077500e059,59,22,23,1,1,"{""Daizen Maeda 56'""}","{""Anthony Elanga 62'""}",F,3,...,4,True,finished,group,Japan,ژاپن,Sweden,سوئد,NaN,NaN
8,679c9c8a5749c4077500e089,95,0,0,0,0,NaN,NaN,R16,5,...,7,False,notstarted,r16,NaN,NaN,NaN,NaN,Winner Match 86,Winner Match 88
9,679c9c8a5749c4077500e08f,101,0,0,0,0,NaN,NaN,SF,7,...,4,False,notstarted,sf,NaN,NaN,NaN,NaN,Winner Match 97,Winner Match 98

================================================================================
HOJA: groups
Filas: 12
Columnas: 6
['_id', 'name', 'teams', 'createdAt', '__v', 'updatedAt']

,_id,name,teams,createdAt,__v,updatedAt
0,698985a46e8cb0bf61b5ac74,A,"[{'team_id': '1', 'mp': '3', 'w': '3', 'l': '0...",2026-02-09T06:58:44.331Z,0,2026-06-25T02:59:29.906Z
1,698985a46e8cb0bf61b5ac7a,B,"[{'team_id': '8', 'mp': '3', 'w': '2', 'l': '0...",2026-02-09T06:58:44.354Z,0,2026-06-24T20:59:32.129Z
2,698985a46e8cb0bf61b5ac80,C,"[{'team_id': '9', 'mp': '3', 'w': '2', 'l': '0...",2026-02-09T06:58:44.360Z,0,2026-06-25T00:03:07.897Z
3,698985a46e8cb0bf61b5ac86,D,"[{'team_id': '13', 'mp': '3', 'w': '2', 'l': '...",2026-02-09T06:58:44.364Z,0,2026-06-26T04:03:56.726Z
4,698985a46e8cb0bf61b5ac8c,E,"[{'team_id': '17', 'mp': '3', 'w': '2', 'l': '...",2026-02-09T06:58:44.367Z,0,2026-06-25T21:59:55.741Z
5,698985a46e8cb0bf61b5ac92,F,"[{'team_id': '21', 'mp': '3', 'w': '2', 'l': '...",2026-02-09T06:58:44.371Z,0,2026-06-26T00:59:38.629Z
6,698985a46e8cb0bf61b5ac98,G,"[{'team_id': '25', 'mp': '3', 'w': '1', 'l': '...",2026-02-09T06:58:44.374Z,0,2026-06-27T05:05:01.320Z
7,698985a46e8cb0bf61b5ac9e,H,"[{'team_id': '29', 'mp': '3', 'w': '2', 'l': '...",2026-02-09T06:58:44.378Z,0,2026-06-27T02:02:41.121Z
8,698985a46e8cb0bf61b5aca4,I,"[{'team_id': '33', 'mp': '3', 'w': '3', 'l': '...",2026-02-09T06:58:44.383Z,0,2026-06-26T21:05:33.086Z
9,698985a46e8cb0bf61b5acaa,J,"[{'team_id': '37', 'mp': '3', 'w': '3', 'l': '...",2026-02-09T06:58:44.388Z,0,2026-06-28T04:00:22.455Z

================================================================================
HOJA: stadiums
Filas: 16
Columnas: 11
['_id', 'id', 'name_en', 'name_fa', 'fifa_name', 'city_en', 'city_fa', 'country_en', 'country_fa', 'capacity', 'region']

,_id,id,name_en,name_fa,fifa_name,city_en,city_fa,country_en,country_fa,capacity,region
0,679c9c8a5749c4077500f001,1,Estadio Azteca,استادیوم آزتکا,Mexico City Stadium,Mexico City,مکزیکوسیتی,Mexico,مکزیک,83000,Central
1,679c9c8a5749c4077500f002,2,Estadio Akron,استادیوم آکرون,Estadio Guadalajara,Guadalajara (Zapopan),گوادالاخارا,Mexico,مکزیک,48000,Central
2,679c9c8a5749c4077500f003,3,Estadio BBVA,استادیوم بی‌بی‌وی‌ای,Estadio Monterrey,Monterrey (Guadalupe),مونتری,Mexico,مکزیک,53500,Central
3,679c9c8a5749c4077500f004,4,AT&T Stadium,استادیوم ای‌تی‌اند‌تی,Dallas Stadium,"Dallas (Arlington, Texas)",دالاس,United States,آمریکا,94000,Central
4,679c9c8a5749c4077500f005,5,NRG Stadium,استادیوم ان‌آر‌جی,Houston Stadium,Houston,هیوستون,United States,آمریکا,72000,Central
5,679c9c8a5749c4077500f006,6,GEHA Field at Arrowhead Stadium,استادیوم اروهد,Kansas City Stadium,Kansas City,کانزاس سیتی,United States,آمریکا,73000,Central
6,679c9c8a5749c4077500f007,7,Mercedes-Benz Stadium,استادیوم مرسدس بنز,Atlanta Stadium,Atlanta,آتلانتا,United States,آمریکا,75000,Eastern
7,679c9c8a5749c4077500f008,8,Hard Rock Stadium,استادیوم هارد راک,Miami Stadium,Miami (Miami Gardens),میامی,United States,آمریکا,65000,Eastern
8,679c9c8a5749c4077500f009,9,Gillette Stadium,استادیوم ژیلت,Boston Stadium,Boston (Foxborough),بوستون,United States,آمریکا,65000,Eastern
9,679c9c8a5749c4077500f010,10,Lincoln Financial Field,استادیوم لینکلن فایننشال,Philadelphia Stadium,Philadelphia,فیلادلفیا,United States,آمریکا,69000,Eastern

In [14]:
games = sheets["games"].copy()

# Pasar nombres de columnas a texto normal
games.columns = [str(c) for c in games.columns]

print("Columnas disponibles en games:")
print(games.columns.tolist())

# Buscar columna de ronda/fase
possible_round_cols = [
    c for c in games.columns
    if any(word in c.lower() for word in ["round", "stage", "phase", "type"])
]

print("\nPosibles columnas de ronda/fase:")
print(possible_round_cols)

# Elegimos una columna probable de ronda
round_col = possible_round_cols[0] if possible_round_cols else None

if round_col is None:
    print("No encontré columna de ronda/fase. Necesitamos mirar manualmente las columnas.")
else:
    print("Columna usada como ronda:", round_col)

    games["round_detected"] = games[round_col].astype(str)

    group_games = games[
        games["round_detected"].str.contains("Group|grupo", case=False, na=False)
    ].copy()

    knockout_games = games[
        ~games["round_detected"].str.contains("Group|grupo", case=False, na=False)
    ].copy()

    group_games.to_excel(OUTPUT_DIR / "live_group_games.xlsx", index=False)
    knockout_games.to_excel(OUTPUT_DIR / "live_knockout_games.xlsx", index=False)

    print("Partidos fase de grupos:", len(group_games))
    print("Partidos eliminación directa:", len(knockout_games))

    print("\nRondas detectadas:")
    display(
        games["round_detected"]
        .value_counts()
        .reset_index()
        .rename(columns={"index": "round", "round_detected": "matches"})
    )

    print("\nMuestra eliminación directa:")
    display(knockout_games.head(20))

Columnas disponibles en games:
['_id', 'id', 'home_team_id', 'away_team_id', 'home_score', 'away_score', 'home_scorers', 'away_scorers', 'group', 'matchday', 'local_date', 'persian_date', 'stadium_id', 'finished', 'time_elapsed', 'type', 'home_team_name_en', 'home_team_name_fa', 'away_team_name_en', 'away_team_name_fa', 'home_team_label', 'away_team_label']

Posibles columnas de ronda/fase:
['type']
Columna usada como ronda: type
Partidos fase de grupos: 72
Partidos eliminación directa: 32

Rondas detectadas:

  matches  count
0   group     72
1     r32     16
2     r16      8
3      qf      4
4      sf      2
5   final      1
6   third      1

Muestra eliminación directa:

,_id,id,home_team_id,away_team_id,home_score,away_score,home_scorers,away_scorers,group,matchday,...,finished,time_elapsed,type,home_team_name_en,home_team_name_fa,away_team_name_en,away_team_name_fa,home_team_label,away_team_label,round_detected
8,679c9c8a5749c4077500e089,95,0,0,0,0,NaN,NaN,R16,5,...,False,notstarted,r16,NaN,NaN,NaN,NaN,Winner Match 86,Winner Match 88,r16
9,679c9c8a5749c4077500e08f,101,0,0,0,0,NaN,NaN,SF,7,...,False,notstarted,sf,NaN,NaN,NaN,NaN,Winner Match 97,Winner Match 98,sf
10,679c9c8a5749c4077500e090,102,0,0,0,0,NaN,NaN,SF,7,...,False,notstarted,sf,NaN,NaN,NaN,NaN,Winner Match 99,Winner Match 100,sf
22,679c9c8a5749c4077500e080,86,37,30,0,0,NaN,NaN,R32,4,...,False,notstarted,r32,Argentina,آرژانتین,Cape Verde,کیپ ورد,Winner Group J,Runner-up Group H,r32
23,679c9c8a5749c4077500e082,88,15,26,0,0,NaN,NaN,R32,4,...,False,notstarted,r32,Australia,استرالیا,Egypt,مصر,Runner-up Group D,Runner-up Group G,r32
24,679c9c8a5749c4077500e08e,100,0,0,0,0,NaN,NaN,QF,6,...,False,notstarted,qf,NaN,NaN,NaN,NaN,Winner Match 95,Winner Match 96,qf
33,679c9c8a5749c4077500e081,87,0,0,0,0,NaN,NaN,R32,4,...,False,notstarted,r32,NaN,NaN,NaN,NaN,Winner Group K,3rd Group D/E/I/J/L,r32
34,679c9c8a5749c4077500e08c,98,0,0,0,0,NaN,NaN,QF,6,...,False,notstarted,qf,NaN,NaN,NaN,NaN,Winner Match 93,Winner Match 94,qf
51,679c9c8a5749c4077500e076,76,9,22,0,0,NaN,NaN,R32,4,...,False,notstarted,r32,Brazil,برزیل,Japan,ژاپن,Winner Group C,Runner-up Group F,r32
52,679c9c8a5749c4077500e07d,83,0,0,0,0,NaN,NaN,R32,4,...,False,notstarted,r32,NaN,NaN,NaN,NaN,Runner-up Group K,Runner-up Group L,r32
53,679c9c8a5749c4077500e07f,85,8,0,0,0,NaN,NaN,R32,4,...,False,notstarted,r32,Switzerland,سوئیس,NaN,NaN,Winner Group B,3rd Group E/F/G/I/J,r32
54,679c9c8a5749c4077500e087,93,0,0,0,0,NaN,NaN,R16,5,...,False,notstarted,r16,NaN,NaN,NaN,NaN,Winner Match 83,Winner Match 84,r16
55,679c9c8a5749c4077500e08a,96,0,0,0,0,NaN,NaN,R16,5,...,False,notstarted,r16,NaN,NaN,NaN,NaN,Winner Match 85,Winner Match 87,r16
66,679c9c8a5749c4077500e073,73,2,5,0,0,NaN,NaN,R32,4,...,False,notstarted,r32,South Africa,آفریقای جنوبی,Canada,کانادا,Runner-up Group A,Runner-up Group B,r32
67,679c9c8a5749c4077500e077,77,33,0,0,0,NaN,NaN,R32,4,...,False,notstarted,r32,France,فرانسه,NaN,NaN,Winner Group I,3rd Group C/D/F/G/H,r32
68,679c9c8a5749c4077500e07e,84,0,0,0,0,NaN,NaN,R32,4,...,False,notstarted,r32,NaN,NaN,NaN,NaN,Winner Group H,Runner-up Group J,r32
69,679c9c8a5749c4077500e084,90,0,0,0,0,NaN,NaN,R16,5,...,False,notstarted,r16,NaN,NaN,NaN,NaN,Winner Match 73,Winner Match 75,r16
70,679c9c8a5749c4077500e086,92,0,0,0,0,NaN,NaN,R16,5,...,False,notstarted,r16,NaN,NaN,NaN,NaN,Winner Match 79,Winner Match 80,r16
71,679c9c8a5749c4077500e088,94,0,0,0,0,NaN,NaN,R16,5,...,False,notstarted,r16,NaN,NaN,NaN,NaN,Winner Match 81,Winner Match 82,r16
76,679c9c8a5749c4077500e085,91,0,0,0,0,NaN,NaN,R16,5,...,False,notstarted,r16,NaN,NaN,NaN,NaN,Winner Match 76,Winner Match 78,r16

In [15]:
import pandas as pd
import numpy as np
from pathlib import Path

print("Creando tabla normalizada de partidos reales...")

live_file = OUTPUT_DIR / "worldcup_open_live_data.xlsx"

sheets = pd.read_excel(live_file, sheet_name=None)

games = sheets["games"].copy()
teams = sheets["teams"].copy()
groups = sheets["groups"].copy()

# Normalizar nombres de columnas
games.columns = [str(c).strip() for c in games.columns]

print("Filas en games:", len(games))
print("Columnas disponibles:")
print(games.columns.tolist())

def find_col(df, keywords, required=False):
    """
    Busca una columna que contenga todas o algunas palabras clave.
    """
    cols = df.columns.tolist()
    cols_lower = {c: c.lower() for c in cols}
    
    # Primero busca coincidencias fuertes
    for col, low in cols_lower.items():
        if all(k.lower() in low for k in keywords):
            return col
    
    # Después busca coincidencias parciales
    for col, low in cols_lower.items():
        if any(k.lower() in low for k in keywords):
            return col
    
    if required:
        raise ValueError(f"No encontré columna para keywords: {keywords}")
    
    return None

# Detectar columnas probables
id_col = find_col(games, ["id"])
date_col = find_col(games, ["date"])
round_col = find_col(games, ["round"]) or find_col(games, ["stage"]) or find_col(games, ["phase"])
status_col = find_col(games, ["status"])

home_team_col = (
    find_col(games, ["home", "name"]) or
    find_col(games, ["home_team"]) or
    find_col(games, ["home"])
)

away_team_col = (
    find_col(games, ["away", "name"]) or
    find_col(games, ["away_team"]) or
    find_col(games, ["away"])
)

home_score_col = (
    find_col(games, ["home", "score"]) or
    find_col(games, ["home", "goal"]) or
    find_col(games, ["score1"])
)

away_score_col = (
    find_col(games, ["away", "score"]) or
    find_col(games, ["away", "goal"]) or
    find_col(games, ["score2"])
)

group_col = find_col(games, ["group"])

print("\nColumnas detectadas:")
print("id_col:", id_col)
print("date_col:", date_col)
print("round_col:", round_col)
print("status_col:", status_col)
print("home_team_col:", home_team_col)
print("away_team_col:", away_team_col)
print("home_score_col:", home_score_col)
print("away_score_col:", away_score_col)
print("group_col:", group_col)

# Crear tabla normalizada
official_games = pd.DataFrame()

official_games["match_id"] = games[id_col] if id_col else range(1, len(games) + 1)
official_games["date"] = games[date_col] if date_col else None
official_games["round"] = games[round_col] if round_col else None
official_games["status"] = games[status_col] if status_col else None
official_games["group"] = games[group_col] if group_col else None
official_games["team_a"] = games[home_team_col] if home_team_col else None
official_games["team_b"] = games[away_team_col] if away_team_col else None
official_games["goals_a"] = games[home_score_col] if home_score_col else None
official_games["goals_b"] = games[away_score_col] if away_score_col else None

# Limpiar textos
for col in ["round", "status", "group", "team_a", "team_b"]:
    official_games[col] = official_games[col].astype(str).replace("nan", "")

# Convertir goles
official_games["goals_a"] = pd.to_numeric(official_games["goals_a"], errors="coerce")
official_games["goals_b"] = pd.to_numeric(official_games["goals_b"], errors="coerce")

# Detectar partidos terminados
official_games["is_finished"] = official_games["status"].str.contains(
    "finished|complete|full|ft|final",
    case=False,
    na=False
)

# Determinar ganador real si hay resultado
def get_real_winner(row):
    if pd.isna(row["goals_a"]) or pd.isna(row["goals_b"]):
        return ""
    
    if row["goals_a"] > row["goals_b"]:
        return row["team_a"]
    elif row["goals_b"] > row["goals_a"]:
        return row["team_b"]
    else:
        return "Draw"

official_games["real_winner"] = official_games.apply(get_real_winner, axis=1)

# Clasificar fase
official_games["is_group_stage"] = official_games["round"].str.contains(
    "group|grupo",
    case=False,
    na=False
)

official_games["is_knockout"] = ~official_games["is_group_stage"]

# Ordenar
official_games = official_games.sort_values(["date", "match_id"], na_position="last").reset_index(drop=True)

# Exportar
output_file = OUTPUT_DIR / "official_games_normalized.xlsx"
official_games.to_excel(output_file, index=False)

print("\nArchivo creado:")
print(output_file)

print("\nResumen:")
print("Partidos totales:", len(official_games))
print("Fase de grupos:", official_games["is_group_stage"].sum())
print("Eliminación directa:", official_games["is_knockout"].sum())
print("Terminados:", official_games["is_finished"].sum())

print("\nRondas detectadas:")
display(
    official_games["round"]
    .value_counts()
    .reset_index()
    .rename(columns={"index": "round", "round": "matches"})
)

display(official_games.head(30))

Creando tabla normalizada de partidos reales...
Filas en games: 104
Columnas disponibles:
['_id', 'id', 'home_team_id', 'away_team_id', 'home_score', 'away_score', 'home_scorers', 'away_scorers', 'group', 'matchday', 'local_date', 'persian_date', 'stadium_id', 'finished', 'time_elapsed', 'type', 'home_team_name_en', 'home_team_name_fa', 'away_team_name_en', 'away_team_name_fa', 'home_team_label', 'away_team_label']

Columnas detectadas:
id_col: _id
date_col: local_date
round_col: None
status_col: None
home_team_col: home_team_name_en
away_team_col: away_team_name_en
home_score_col: home_score
away_score_col: away_score
group_col: group

Archivo creado:
c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Data\Processed\official_games_normalized.xlsx

Resumen:
Partidos totales: 104
Fase de grupos: 0
Eliminación directa: 104
Terminados: 0

Rondas detectadas:

Empty DataFrame
Columns: [matches, count]
Index: []

,match_id,date,round,status,group,team_a,team_b,goals_a,goals_b,is_finished,real_winner,is_group_stage,is_knockout
0,679c9c8a5749c4077500e001,06/11/2026 13:00,NaN,NaN,A,Mexico,South Africa,2,0,False,Mexico,False,True
1,679c9c8a5749c4077500e002,06/11/2026 20:00,NaN,NaN,A,South Korea,Czech Republic,2,1,False,South Korea,False,True
2,679c9c8a5749c4077500e003,06/12/2026 15:00,NaN,NaN,B,Canada,Bosnia and Herzegovina,1,1,False,Draw,False,True
3,679c9c8a5749c4077500e004,06/12/2026 18:00,NaN,NaN,D,United States,Paraguay,4,1,False,United States,False,True
4,679c9c8a5749c4077500e008,06/13/2026 12:00,NaN,NaN,B,Qatar,Switzerland,1,1,False,Draw,False,True
5,679c9c8a5749c4077500e007,06/13/2026 18:00,NaN,NaN,C,Brazil,Morocco,1,1,False,Draw,False,True
6,679c9c8a5749c4077500e005,06/13/2026 21:00,NaN,NaN,C,Haiti,Scotland,0,1,False,Scotland,False,True
7,679c9c8a5749c4077500e006,06/13/2026 21:00,NaN,NaN,D,Australia,Turkey,2,0,False,Australia,False,True
8,679c9c8a5749c4077500e010,06/14/2026 12:00,NaN,NaN,E,Germany,Curaçao,7,1,False,Germany,False,True
9,679c9c8a5749c4077500e011,06/14/2026 15:00,NaN,NaN,F,Netherlands,Japan,2,2,False,Draw,False,True
10,679c9c8a5749c4077500e009,06/14/2026 19:00,NaN,NaN,E,Ivory Coast,Ecuador,1,0,False,Ivory Coast,False,True
11,679c9c8a5749c4077500e012,06/14/2026 20:00,NaN,NaN,F,Sweden,Tunisia,5,1,False,Sweden,False,True
12,679c9c8a5749c4077500e014,06/15/2026 12:00,NaN,NaN,H,Spain,Cape Verde,0,0,False,Draw,False,True
13,679c9c8a5749c4077500e015,06/15/2026 12:00,NaN,NaN,G,Belgium,Egypt,1,1,False,Draw,False,True
14,679c9c8a5749c4077500e013,06/15/2026 18:00,NaN,NaN,G,Iran,New Zealand,2,2,False,Draw,False,True
15,679c9c8a5749c4077500e016,06/15/2026 18:00,NaN,NaN,H,Saudi Arabia,Uruguay,1,1,False,Draw,False,True
16,679c9c8a5749c4077500e017,06/16/2026 15:00,NaN,NaN,I,France,Senegal,3,1,False,France,False,True
17,679c9c8a5749c4077500e018,06/16/2026 18:00,NaN,NaN,I,Iraq,Norway,1,4,False,Norway,False,True
18,679c9c8a5749c4077500e019,06/16/2026 20:00,NaN,NaN,J,Argentina,Algeria,3,0,False,Argentina,False,True
19,679c9c8a5749c4077500e020,06/16/2026 21:00,NaN,NaN,J,Austria,Jordan,3,1,False,Austria,False,True
20,679c9c8a5749c4077500e021,06/17/2026 12:00,NaN,NaN,K,Portugal,Democratic Republic of the Congo,1,1,False,Draw,False,True
21,679c9c8a5749c4077500e022,06/17/2026 15:00,NaN,NaN,L,England,Croatia,4,2,False,England,False,True
22,679c9c8a5749c4077500e024,06/17/2026 19:00,NaN,NaN,L,Ghana,Panama,1,0,False,Ghana,False,True
23,679c9c8a5749c4077500e023,06/17/2026 20:00,NaN,NaN,K,Uzbekistan,Colombia,1,3,False,Colombia,False,True
24,679c9c8a5749c4077500e026,06/18/2026 12:00,NaN,NaN,B,Switzerland,Bosnia and Herzegovina,4,1,False,Switzerland,False,True
25,679c9c8a5749c4077500e028,06/18/2026 12:00,NaN,NaN,A,Czech Republic,South Africa,1,1,False,Draw,False,True
26,679c9c8a5749c4077500e027,06/18/2026 15:00,NaN,NaN,B,Canada,Qatar,6,0,False,Canada,False,True
27,679c9c8a5749c4077500e025,06/18/2026 19:00,NaN,NaN,A,Mexico,South Korea,1,0,False,Mexico,False,True
28,679c9c8a5749c4077500e031,06/19/2026 12:00,NaN,NaN,D,United States,Australia,2,0,False,United States,False,True
29,679c9c8a5749c4077500e030,06/19/2026 18:00,NaN,NaN,C,Scotland,Morocco,0,1,False,Morocco,False,True

In [16]:
print("Creando archivo base para Hoja 4...")

official_games = pd.read_excel(OUTPUT_DIR / "official_games_normalized.xlsx")

# Separar partidos
group_games = official_games[official_games["is_group_stage"] == True].copy()
knockout_games = official_games[official_games["is_knockout"] == True].copy()

# Si todavía no hay eliminación directa cargada, dejamos estructura lista igual
if knockout_games.empty:
    print("Atención: la API no trajo partidos de eliminación directa todavía.")
    print("Se creará una estructura base vacía para completar cuando aparezcan los cruces reales.")

# Tabla resumen para Power BI
api_status_summary = pd.DataFrame([{
    "total_matches": len(official_games),
    "group_stage_matches": len(group_games),
    "knockout_matches": len(knockout_games),
    "finished_matches": int(official_games["is_finished"].sum()),
    "source": "WorldCup26 open API",
    "last_refresh": pd.Timestamp.now()
}])

# Tabla de rondas
rounds_summary = (
    official_games
    .groupby("round", as_index=False)
    .agg(
        matches=("match_id", "count"),
        finished_matches=("is_finished", "sum")
    )
    .sort_values("round")
)

# Exportar archivo base
output_file = OUTPUT_DIR / "official_tournament_bracket.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
    official_games.to_excel(writer, sheet_name="official_games", index=False)
    group_games.to_excel(writer, sheet_name="group_games", index=False)
    knockout_games.to_excel(writer, sheet_name="knockout_games", index=False)
    api_status_summary.to_excel(writer, sheet_name="api_status_summary", index=False)
    rounds_summary.to_excel(writer, sheet_name="rounds_summary", index=False)

print("Archivo creado correctamente:")
print(output_file)

display(api_status_summary)
display(rounds_summary)
display(knockout_games.head(30))

Creando archivo base para Hoja 4...
Archivo creado correctamente:
c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Data\Processed\official_tournament_bracket.xlsx

,total_matches,group_stage_matches,knockout_matches,finished_matches,source,last_refresh
0,104,0,104,0,WorldCup26 open API,2026-06-28 01:24:41.610007

Empty DataFrame
Columns: [round, matches, finished_matches]
Index: []

,match_id,date,round,status,group,team_a,team_b,goals_a,goals_b,is_finished,real_winner,is_group_stage,is_knockout
0,679c9c8a5749c4077500e001,06/11/2026 13:00,NaN,NaN,A,Mexico,South Africa,2,0,False,Mexico,False,True
1,679c9c8a5749c4077500e002,06/11/2026 20:00,NaN,NaN,A,South Korea,Czech Republic,2,1,False,South Korea,False,True
2,679c9c8a5749c4077500e003,06/12/2026 15:00,NaN,NaN,B,Canada,Bosnia and Herzegovina,1,1,False,Draw,False,True
3,679c9c8a5749c4077500e004,06/12/2026 18:00,NaN,NaN,D,United States,Paraguay,4,1,False,United States,False,True
4,679c9c8a5749c4077500e008,06/13/2026 12:00,NaN,NaN,B,Qatar,Switzerland,1,1,False,Draw,False,True
5,679c9c8a5749c4077500e007,06/13/2026 18:00,NaN,NaN,C,Brazil,Morocco,1,1,False,Draw,False,True
6,679c9c8a5749c4077500e005,06/13/2026 21:00,NaN,NaN,C,Haiti,Scotland,0,1,False,Scotland,False,True
7,679c9c8a5749c4077500e006,06/13/2026 21:00,NaN,NaN,D,Australia,Turkey,2,0,False,Australia,False,True
8,679c9c8a5749c4077500e010,06/14/2026 12:00,NaN,NaN,E,Germany,Curaçao,7,1,False,Germany,False,True
9,679c9c8a5749c4077500e011,06/14/2026 15:00,NaN,NaN,F,Netherlands,Japan,2,2,False,Draw,False,True
10,679c9c8a5749c4077500e009,06/14/2026 19:00,NaN,NaN,E,Ivory Coast,Ecuador,1,0,False,Ivory Coast,False,True
11,679c9c8a5749c4077500e012,06/14/2026 20:00,NaN,NaN,F,Sweden,Tunisia,5,1,False,Sweden,False,True
12,679c9c8a5749c4077500e014,06/15/2026 12:00,NaN,NaN,H,Spain,Cape Verde,0,0,False,Draw,False,True
13,679c9c8a5749c4077500e015,06/15/2026 12:00,NaN,NaN,G,Belgium,Egypt,1,1,False,Draw,False,True
14,679c9c8a5749c4077500e013,06/15/2026 18:00,NaN,NaN,G,Iran,New Zealand,2,2,False,Draw,False,True
15,679c9c8a5749c4077500e016,06/15/2026 18:00,NaN,NaN,H,Saudi Arabia,Uruguay,1,1,False,Draw,False,True
16,679c9c8a5749c4077500e017,06/16/2026 15:00,NaN,NaN,I,France,Senegal,3,1,False,France,False,True
17,679c9c8a5749c4077500e018,06/16/2026 18:00,NaN,NaN,I,Iraq,Norway,1,4,False,Norway,False,True
18,679c9c8a5749c4077500e019,06/16/2026 20:00,NaN,NaN,J,Argentina,Algeria,3,0,False,Argentina,False,True
19,679c9c8a5749c4077500e020,06/16/2026 21:00,NaN,NaN,J,Austria,Jordan,3,1,False,Austria,False,True
20,679c9c8a5749c4077500e021,06/17/2026 12:00,NaN,NaN,K,Portugal,Democratic Republic of the Congo,1,1,False,Draw,False,True
21,679c9c8a5749c4077500e022,06/17/2026 15:00,NaN,NaN,L,England,Croatia,4,2,False,England,False,True
22,679c9c8a5749c4077500e024,06/17/2026 19:00,NaN,NaN,L,Ghana,Panama,1,0,False,Ghana,False,True
23,679c9c8a5749c4077500e023,06/17/2026 20:00,NaN,NaN,K,Uzbekistan,Colombia,1,3,False,Colombia,False,True
24,679c9c8a5749c4077500e026,06/18/2026 12:00,NaN,NaN,B,Switzerland,Bosnia and Herzegovina,4,1,False,Switzerland,False,True
25,679c9c8a5749c4077500e028,06/18/2026 12:00,NaN,NaN,A,Czech Republic,South Africa,1,1,False,Draw,False,True
26,679c9c8a5749c4077500e027,06/18/2026 15:00,NaN,NaN,B,Canada,Qatar,6,0,False,Canada,False,True
27,679c9c8a5749c4077500e025,06/18/2026 19:00,NaN,NaN,A,Mexico,South Korea,1,0,False,Mexico,False,True
28,679c9c8a5749c4077500e031,06/19/2026 12:00,NaN,NaN,D,United States,Australia,2,0,False,United States,False,True
29,679c9c8a5749c4077500e030,06/19/2026 18:00,NaN,NaN,C,Scotland,Morocco,0,1,False,Morocco,False,True

In [1]:
import pandas as pd
import numpy as np
import re
import unicodedata
from pathlib import Path

print("Generando simulación sobre bracket real del Mundial 2026...")

N_SIMULATIONS = 25000
RANDOM_SEED = 42
rng = np.random.default_rng(RANDOM_SEED)

# =========================
# 1. Buscar archivos
# =========================

search_roots = [
    Path.cwd(),
    Path.cwd().parent,
    Path.cwd().parent.parent
]

bracket_files = []
ranking_files = []
simulator_files = []

for root in search_roots:
    if root.exists():
        bracket_files.extend(list(root.rglob("official_tournament_bracket_normalized.xlsx")))
        ranking_files.extend(list(root.rglob("world_cup_live_power_ranking.xlsx")))
        simulator_files.extend(list(root.rglob("world_cup_match_simulator.xlsx")))

bracket_files = list(dict.fromkeys(bracket_files))
ranking_files = list(dict.fromkeys(ranking_files))
simulator_files = list(dict.fromkeys(simulator_files))

if not bracket_files:
    raise FileNotFoundError("No encontré official_tournament_bracket_normalized.xlsx")

if not ranking_files:
    raise FileNotFoundError("No encontré world_cup_live_power_ranking.xlsx")

if not simulator_files:
    raise FileNotFoundError("No encontré world_cup_match_simulator.xlsx")

bracket_file = bracket_files[0]
ranking_file = ranking_files[0]
simulator_file = simulator_files[0]

print("Bracket real:", bracket_file)
print("Ranking:", ranking_file)
print("Simulador:", simulator_file)

# =========================
# 2. Cargar datos
# =========================

bracket_sheets = pd.read_excel(bracket_file, sheet_name=None)

knockout = bracket_sheets["knockout_bracket"].copy()
teams_api = bracket_sheets["teams"].copy()
ranking = pd.read_excel(ranking_file)
simulator = pd.read_excel(simulator_file)

# =========================
# 3. Normalizar nombres
# =========================

name_aliases = {
    "Curaçao": "Curacao",
    "Curacao": "Curacao",
    "Czechia": "Czech Republic",
    "Czech Republic": "Czech Republic",
    "Democratic Republic of the Congo": "Congo",
    "DR Congo": "Congo",
    "Congo DR": "Congo",
    "Congo": "Congo",
    "United States": "United States",
    "USA": "United States",
}

def normalize_text(value):
    if pd.isna(value):
        return ""
    value = str(value).strip()
    value = unicodedata.normalize("NFKD", value)
    value = "".join([c for c in value if not unicodedata.combining(c)])
    return value

def canonical_team(value):
    if pd.isna(value):
        return ""
    
    value = str(value).strip()
    
    if value in name_aliases:
        return name_aliases[value]
    
    value_clean = normalize_text(value)
    
    for original, mapped in name_aliases.items():
        if normalize_text(original).lower() == value_clean.lower():
            return mapped
    
    return value

for col in ["team_a", "team_b", "real_winner"]:
    if col in knockout.columns:
        knockout[col] = knockout[col].apply(canonical_team)

ranking["team"] = ranking["team"].apply(canonical_team)

if "team_display" not in ranking.columns:
    ranking["team_display"] = ranking["team"]

ranking = ranking.drop_duplicates(subset=["team"]).reset_index(drop=True)

team_info = ranking.set_index("team").to_dict("index")

def team_display(team):
    team = canonical_team(team)
    return team_info.get(team, {}).get("team_display", team)

def team_confederation(team):
    team = canonical_team(team)
    return team_info.get(team, {}).get("confederation", "")

def team_ranking(team):
    team = canonical_team(team)
    return team_info.get(team, {}).get("ranking", 99)

def team_power(team):
    team = canonical_team(team)
    return float(team_info.get(team, {}).get("power_score_live", 0.50))

def team_rating(team):
    team = canonical_team(team)
    return float(team_info.get(team, {}).get("rating", 1500))

# =========================
# 4. Resolver terceros pendientes
# =========================

def parse_candidates(text):
    if pd.isna(text) or str(text).strip() == "":
        return []
    
    text = str(text)
    
    matches = re.findall(r"([A-L]\d)\s+([^,]+)", text)
    
    candidates = []
    
    for slot, team in matches:
        candidates.append({
            "slot": slot,
            "team": canonical_team(team.strip())
        })
    
    return candidates

pending_slots = []

for idx, row in knockout.iterrows():
    if row["round_type"] != "r32":
        continue
    
    for side in ["a", "b"]:
        status_col = f"team_{side}_status"
        candidates_col = f"team_{side}_andidates"
        
        # Por si la columna está bien escrita como candidates
        candidates_col = f"team_{side}_candidates"
        
        if status_col in knockout.columns and candidates_col in knockout.columns:
            if str(row[status_col]) == "pending_third_place_assignment":
                candidates = parse_candidates(row[candidates_col])
                pending_slots.append({
                    "row_index": idx,
                    "side": side,
                    "match_id": row["match_id"],
                    "candidates": candidates
                })

# Terceros ya asignados oficialmente
used_third_place_teams = set()

for _, row in knockout[knockout["round_type"] == "r32"].iterrows():
    for side in ["a", "b"]:
        raw_col = f"team_{side}_raw_label"
        team_col = f"team_{side}"
        status_col = f"team_{side}_status"
        
        raw_label = str(row.get(raw_col, ""))
        status = str(row.get(status_col, ""))
        team = canonical_team(row.get(team_col, ""))
        
        if "3rd Group" in raw_label and status != "pending_third_place_assignment" and team:
            used_third_place_teams.add(team)

third_place_assignments = []

# Resolver primero los slots con menos candidatos
pending_slots = sorted(pending_slots, key=lambda x: len(x["candidates"]))

for slot in pending_slots:
    available = [
        c["team"]
        for c in slot["candidates"]
        if c["team"] not in used_third_place_teams
    ]
    
    if not available:
        available = [c["team"] for c in slot["candidates"]]
    
    # Elegimos el candidato más fuerte por Power Score
    selected = sorted(
        available,
        key=lambda t: team_power(t),
        reverse=True
    )[0]
    
    used_third_place_teams.add(selected)
    
    team_col = f"team_{slot['side']}"
    status_col = f"team_{slot['side']}_status"
    
    knockout.loc[slot["row_index"], team_col] = selected
    knockout.loc[slot["row_index"], status_col] = "resolved_third_place_model"
    
    third_place_assignments.append({
        "match_id": slot["match_id"],
        "side": slot["side"],
        "selected_team": selected,
        "selected_team_display": team_display(selected),
        "candidate_options": ", ".join([c["team"] for c in slot["candidates"]])
    })

third_place_assignments = pd.DataFrame(third_place_assignments)

print("Terceros pendientes resueltos:")
display(third_place_assignments)

# =========================
# 5. Probabilidades de partidos
# =========================

for col in ["team_a", "team_b"]:
    simulator[col] = simulator[col].apply(canonical_team)

for col in ["win_a_probability", "draw_probability", "win_b_probability"]:
    simulator[col] = pd.to_numeric(simulator[col], errors="coerce")
    if simulator[col].max() > 1:
        simulator[col] = simulator[col] / 100

pair_probs = (
    simulator[
        ["team_a", "team_b", "win_a_probability", "draw_probability", "win_b_probability"]
    ]
    .drop_duplicates(subset=["team_a", "team_b"])
    .copy()
)

advance_prob = {}

for _, row in pair_probs.iterrows():
    a = row["team_a"]
    b = row["team_b"]
    win_a = float(row["win_a_probability"])
    draw = float(row["draw_probability"])
    win_b = float(row["win_b_probability"])
    
    advance_prob[(a, b)] = win_a + draw * 0.5
    advance_prob[(b, a)] = win_b + draw * 0.5

def fallback_probability(team_a, team_b):
    power_diff = team_power(team_a) - team_power(team_b)
    rating_diff = (team_rating(team_a) - team_rating(team_b)) / 600
    
    x = power_diff * 2.5 + rating_diff
    p = 1 / (1 + np.exp(-x))
    
    return float(np.clip(p, 0.05, 0.95))

def get_advance_probability(team_a, team_b):
    team_a = canonical_team(team_a)
    team_b = canonical_team(team_b)
    
    if team_a == team_b:
        return 1.0
    
    if (team_a, team_b) in advance_prob:
        return advance_prob[(team_a, team_b)]
    
    return fallback_probability(team_a, team_b)

# =========================
# 6. Resolver participantes
# =========================

knockout["match_id"] = pd.to_numeric(knockout["match_id"], errors="coerce").astype(int)

match_table = knockout.set_index("match_id").to_dict("index")

def resolve_participant(label, winners, losers=None):
    label = str(label)
    
    if label.startswith("Winner Match"):
        match_id = int(re.findall(r"\d+", label)[0])
        return winners.get(match_id, "")
    
    if label.startswith("Loser Match") and losers is not None:
        match_id = int(re.findall(r"\d+", label)[0])
        return losers.get(match_id, "")
    
    return canonical_team(label)

def play_match(team_a, team_b):
    p_a = get_advance_probability(team_a, team_b)
    return team_a if rng.random() < p_a else team_b

def deterministic_winner(team_a, team_b):
    p_a = get_advance_probability(team_a, team_b)
    
    if p_a >= 0.5:
        return team_a, p_a
    else:
        return team_b, 1 - p_a

round_sequence = ["r32", "r16", "qf", "sf", "final"]

round_probability_cols = {
    "r32": "round_32_probability",
    "r16": "round_16_probability",
    "qf": "quarterfinal_probability",
    "sf": "semifinal_probability",
    "final": "final_probability"
}

teams_in_model = sorted(ranking["team"].unique())

round_counts = {
    team: {
        "round_32_probability": 0,
        "round_16_probability": 0,
        "quarterfinal_probability": 0,
        "semifinal_probability": 0,
        "final_probability": 0,
        "champion_probability": 0
    }
    for team in teams_in_model
}

# =========================
# 7. Simulación Monte Carlo
# =========================

matches_to_simulate = knockout[
    knockout["round_type"].isin(round_sequence)
].copy()

matches_to_simulate = matches_to_simulate.sort_values("match_id")

for _ in range(N_SIMULATIONS):
    winners = {}
    losers = {}
    
    # Contar equipos que arrancan en 16avos
    r32_matches = matches_to_simulate[matches_to_simulate["round_type"] == "r32"]
    
    for _, row in r32_matches.iterrows():
        team_a = resolve_participant(row["team_a"], winners, losers)
        team_b = resolve_participant(row["team_b"], winners, losers)
        
        if team_a in round_counts:
            round_counts[team_a]["round_32_probability"] += 1
        
        if team_b in round_counts:
            round_counts[team_b]["round_32_probability"] += 1
    
    for _, row in matches_to_simulate.iterrows():
        match_id = int(row["match_id"])
        round_type = row["round_type"]
        
        team_a = resolve_participant(row["team_a"], winners, losers)
        team_b = resolve_participant(row["team_b"], winners, losers)
        
        # Si ya hay ganador real, se respeta
        real_winner = canonical_team(row.get("real_winner", ""))
        finished = bool(row.get("finished", False))
        
        if finished and real_winner and real_winner != "Draw":
            winner = real_winner
        else:
            winner = play_match(team_a, team_b)
        
        loser = team_b if winner == team_a else team_a
        
        winners[match_id] = winner
        losers[match_id] = loser
        
        if round_type == "r32":
            if winner in round_counts:
                round_counts[winner]["round_16_probability"] += 1
        
        elif round_type == "r16":
            if winner in round_counts:
                round_counts[winner]["quarterfinal_probability"] += 1
        
        elif round_type == "qf":
            if winner in round_counts:
                round_counts[winner]["semifinal_probability"] += 1
        
        elif round_type == "sf":
            if winner in round_counts:
                round_counts[winner]["final_probability"] += 1
        
        elif round_type == "final":
            if winner in round_counts:
                round_counts[winner]["champion_probability"] += 1

# =========================
# 8. Probabilidades por equipo
# =========================

round_probabilities = []

for team, counts in round_counts.items():
    row = {
        "team": team,
        "team_display": team_display(team),
        "confederation": team_confederation(team),
        "ranking": team_ranking(team),
        "power_score_live": team_power(team),
        "rating": team_rating(team)
    }
    
    for col, value in counts.items():
        row[col] = value / N_SIMULATIONS
    
    round_probabilities.append(row)

round_probabilities = pd.DataFrame(round_probabilities)

round_probabilities = round_probabilities.sort_values(
    "champion_probability",
    ascending=False
).reset_index(drop=True)

top_candidates = round_probabilities.head(8).copy()

confederation_probabilities = (
    round_probabilities
    .groupby("confederation", as_index=False)["champion_probability"]
    .sum()
    .sort_values("champion_probability", ascending=False)
)

surprises = (
    round_probabilities[
        round_probabilities["ranking"] > 8
    ]
    .sort_values("champion_probability", ascending=False)
    .head(5)
    .copy()
)

# =========================
# 9. Bracket proyectado determinístico real
# =========================

projected_rows = []
projected_winners = {}
projected_losers = {}

for _, row in matches_to_simulate.iterrows():
    match_id = int(row["match_id"])
    round_type = row["round_type"]
    
    team_a = resolve_participant(row["team_a"], projected_winners, projected_losers)
    team_b = resolve_participant(row["team_b"], projected_winners, projected_losers)
    
    real_winner = canonical_team(row.get("real_winner", ""))
    finished = bool(row.get("finished", False))
    
    if finished and real_winner and real_winner != "Draw":
        winner = real_winner
        winner_probability = 1.0
    else:
        winner, winner_probability = deterministic_winner(team_a, team_b)
    
    loser = team_b if winner == team_a else team_a
    
    projected_winners[match_id] = winner
    projected_losers[match_id] = loser
    
    projected_rows.append({
        "match_id": match_id,
        "round_type": round_type,
        "date": row.get("date", ""),
        "team_a": team_a,
        "team_b": team_b,
        "team_a_display": team_display(team_a),
        "team_b_display": team_display(team_b),
        "projected_winner": winner,
        "projected_winner_display": team_display(winner),
        "winner_probability": winner_probability,
        "next_match_id": row.get("next_match_id", ""),
        "bracket_side": row.get("bracket_side", "")
    })

projected_bracket = pd.DataFrame(projected_rows)

final_projected = projected_bracket[projected_bracket["round_type"] == "final"].iloc[0]
champion_projected = final_projected["projected_winner"]

champion_probs = round_probabilities[
    round_probabilities["team"] == champion_projected
].iloc[0]

round_progress_champion = pd.DataFrame([
    {
        "round": "16avos",
        "probability": champion_probs["round_32_probability"]
    },
    {
        "round": "Octavos",
        "probability": champion_probs["round_16_probability"]
    },
    {
        "round": "Cuartos",
        "probability": champion_probs["quarterfinal_probability"]
    },
    {
        "round": "Semifinales",
        "probability": champion_probs["semifinal_probability"]
    },
    {
        "round": "Final",
        "probability": champion_probs["final_probability"]
    },
    {
        "round": "Campeón",
        "probability": champion_probs["champion_probability"]
    }
])

sf_projected = projected_bracket[projected_bracket["round_type"] == "sf"].copy()

key_cards = pd.DataFrame([{
    "champion": champion_projected,
    "champion_display": team_display(champion_projected),
    "champion_probability": champion_probs["champion_probability"],
    "final_probability": champion_probs["final_probability"],
    "semifinal_probability": champion_probs["semifinal_probability"],
    "teams_simulated": len(teams_in_model),
    "simulations": N_SIMULATIONS,
    "final_team_a_display": final_projected["team_a_display"],
    "final_team_b_display": final_projected["team_b_display"],
    "final_winner_display": final_projected["projected_winner_display"],
    "final_match_probability": final_projected["winner_probability"],
    "semi_1_team_a_display": sf_projected.iloc[0]["team_a_display"],
    "semi_1_team_b_display": sf_projected.iloc[0]["team_b_display"],
    "semi_1_winner_display": sf_projected.iloc[0]["projected_winner_display"],
    "semi_1_probability": sf_projected.iloc[0]["winner_probability"],
    "semi_2_team_a_display": sf_projected.iloc[1]["team_a_display"],
    "semi_2_team_b_display": sf_projected.iloc[1]["team_b_display"],
    "semi_2_winner_display": sf_projected.iloc[1]["projected_winner_display"],
    "semi_2_probability": sf_projected.iloc[1]["winner_probability"],
}])

# =========================
# 10. Exportar para Power BI
# =========================

output_file = bracket_file.parent / "world_cup_tournament_simulation_real_bracket.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
    key_cards.to_excel(writer, sheet_name="key_cards_real", index=False)
    round_probabilities.to_excel(writer, sheet_name="round_probabilities_real", index=False)
    top_candidates.to_excel(writer, sheet_name="top_candidates_real", index=False)
    round_progress_champion.to_excel(writer, sheet_name="round_progress_champion_real", index=False)
    confederation_probabilities.to_excel(writer, sheet_name="confederation_probabilities_real", index=False)
    surprises.to_excel(writer, sheet_name="surprises_real", index=False)
    projected_bracket.to_excel(writer, sheet_name="projected_bracket_real", index=False)
    third_place_assignments.to_excel(writer, sheet_name="third_place_assignments", index=False)

print("Archivo creado correctamente:")
print(output_file)

print("\nCampeón proyectado:")
display(key_cards)

print("\nTop 8 candidatos:")
display(top_candidates[[
    "team_display",
    "champion_probability",
    "final_probability",
    "semifinal_probability",
    "confederation"
]])

print("\nBracket proyectado real:")
display(projected_bracket)

Generando simulación sobre bracket real del Mundial 2026...
Bracket real: c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Notebooks\official_tournament_bracket_normalized.xlsx
Ranking: c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Notebooks\world_cup_live_power_ranking.xlsx
Simulador: c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Notebooks\world_cup_match_simulator.xlsx
Terceros pendientes resueltos:

,match_id,side,selected_team,selected_team_display,candidate_options
0,77,b,Sweden,🇸🇪 Sweden,"Paraguay, Sweden"
1,79,b,Senegal,🇸🇳 Senegal,"Ecuador, Sweden, Senegal"
2,82,b,Algeria,🇩🇿 Algeria,"Ecuador, Senegal, Algeria"
3,80,b,Ecuador,🇪🇨 Ecuador,"Ecuador, Senegal, Algeria, Congo"
4,85,b,Senegal,🇸🇳 Senegal,"Ecuador, Sweden, Senegal, Algeria"
5,87,b,Ghana,🇬🇭 Ghana,"Paraguay, Ecuador, Senegal, Algeria, Ghana"

Archivo creado correctamente:
c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Notebooks\world_cup_tournament_simulation_real_bracket.xlsx

Campeón proyectado:

c:\Users\Samsung\AppData\Local\Programs\Python\Python314\Lib\site-packages\openpyxl\workbook\child.py:99: UserWarning: Title is more than 31 characters. Some applications may not be able to read the file
  warnings.warn("Title is more than 31 characters. Some applications may not be able to read the file")

,champion,champion_display,champion_probability,final_probability,semifinal_probability,teams_simulated,simulations,final_team_a_display,final_team_b_display,final_winner_display,final_match_probability,semi_1_team_a_display,semi_1_team_b_display,semi_1_winner_display,semi_1_probability,semi_2_team_a_display,semi_2_team_b_display,semi_2_winner_display,semi_2_probability
0,Spain,🇪🇸 Spain,0.26056,0.4282,0.67032,48,25000,🇪🇸 Spain,🇦🇷 Argentina,🇪🇸 Spain,0.500745,🇫🇷 France,🇪🇸 Spain,🇪🇸 Spain,0.573649,🇧🇷 Brazil,🇦🇷 Argentina,🇦🇷 Argentina,0.684554

Top 8 candidatos:

,team_display,champion_probability,final_probability,semifinal_probability,confederation
0,🇦🇷 Argentina,0.36704,0.63288,0.79612,CONMEBOL
1,🇪🇸 Spain,0.26056,0.42820,0.67032,UEFA
2,🇫🇷 France,0.16492,0.30696,0.57580,UEFA
3,🇧🇷 Brazil,0.06688,0.16688,0.40936,CONMEBOL
4,🇳🇱 Netherlands,0.06092,0.13532,0.30320,UEFA
5,🇵🇹 Portugal,0.03116,0.07964,0.18884,UEFA
6,🇯🇵 Japan,0.01380,0.05148,0.17920,AFC
7,🇨🇴 Colombia,0.01028,0.05032,0.11340,CONMEBOL

Bracket proyectado real:

,match_id,round_type,date,team_a,team_b,team_a_display,team_b_display,projected_winner,projected_winner_display,winner_probability,next_match_id,bracket_side
0,73,r32,06/28/2026 12:00,South Africa,Canada,🇿🇦 South Africa,🇨🇦 Canada,Canada,🇨🇦 Canada,0.819221,90.0,Lado A / Semifinal 101
1,74,r32,06/29/2026 16:30,Germany,Paraguay,🇩🇪 Germany,🇵🇾 Paraguay,Germany,🇩🇪 Germany,0.693839,89.0,Lado A / Semifinal 101
2,75,r32,06/29/2026 19:00,Netherlands,Morocco,🇳🇱 Netherlands,🇲🇦 Morocco,Netherlands,🇳🇱 Netherlands,0.711783,90.0,Lado A / Semifinal 101
3,76,r32,06/29/2026 12:00,Brazil,Japan,🇧🇷 Brazil,🇯🇵 Japan,Brazil,🇧🇷 Brazil,0.635251,91.0,Lado B / Semifinal 102
4,77,r32,06/30/2026 17:00,France,Sweden,🇫🇷 France,🇸🇪 Sweden,France,🇫🇷 France,0.951204,89.0,Lado A / Semifinal 101
5,78,r32,06/30/2026 12:00,Ivory Coast,Norway,🇨🇮 Ivory Coast,🇳🇴 Norway,Norway,🇳🇴 Norway,0.881221,91.0,Lado B / Semifinal 102
6,79,r32,06/30/2026 19:00,Mexico,Senegal,🇲🇽 Mexico,🇸🇳 Senegal,Senegal,🇸🇳 Senegal,0.652077,92.0,Lado B / Semifinal 102
7,80,r32,07/01/2026 12:00,Belgium,Ecuador,🇧🇪 Belgium,🇪🇨 Ecuador,Ecuador,🇪🇨 Ecuador,0.508031,92.0,Lado B / Semifinal 102
8,81,r32,07/01/2026 17:00,United States,Bosnia and Herzegovina,🇺🇸 United States,🇧🇦 Bosnia and Herzegovina,United States,🇺🇸 United States,0.574631,94.0,Lado A / Semifinal 101
9,82,r32,07/01/2026 13:00,Belgium,Algeria,🇧🇪 Belgium,🇩🇿 Algeria,Belgium,🇧🇪 Belgium,0.634218,94.0,Lado A / Semifinal 101
10,83,r32,07/02/2026 19:00,Portugal,Croatia,🇵🇹 Portugal,🇭🇷 Croatia,Portugal,🇵🇹 Portugal,0.723123,93.0,Lado A / Semifinal 101
11,84,r32,07/02/2026 12:00,Spain,Austria,🇪🇸 Spain,🇦🇹 Austria,Spain,🇪🇸 Spain,0.939592,93.0,Lado A / Semifinal 101
12,85,r32,07/02/2026 20:00,Switzerland,Senegal,🇨🇭 Switzerland,🇸🇳 Senegal,Senegal,🇸🇳 Senegal,0.536023,96.0,Lado B / Semifinal 102
13,86,r32,07/03/2026 18:00,Argentina,Cape Verde,🇦🇷 Argentina,🇨🇻 Cape Verde,Argentina,🇦🇷 Argentina,0.959842,95.0,Lado B / Semifinal 102
14,87,r32,07/03/2026 20:30,Colombia,Ghana,🇨🇴 Colombia,🇬🇭 Ghana,Colombia,🇨🇴 Colombia,0.940755,96.0,Lado B / Semifinal 102
15,88,r32,07/03/2026 13:00,Australia,Egypt,🇦🇺 Australia,🇪🇬 Egypt,Australia,🇦🇺 Australia,0.711906,95.0,Lado B / Semifinal 102
16,89,r16,07/04/2026 17:00,Germany,France,🇩🇪 Germany,🇫🇷 France,France,🇫🇷 France,0.862534,97.0,Lado A / Semifinal 101
17,90,r16,07/04/2026 12:00,Canada,Netherlands,🇨🇦 Canada,🇳🇱 Netherlands,Netherlands,🇳🇱 Netherlands,0.891417,97.0,Lado A / Semifinal 101
18,91,r16,07/05/2026 16:00,Brazil,Norway,🇧🇷 Brazil,🇳🇴 Norway,Brazil,🇧🇷 Brazil,0.770238,99.0,Lado B / Semifinal 102
19,92,r16,07/05/2026 18:00,Senegal,Ecuador,🇸🇳 Senegal,🇪🇨 Ecuador,Senegal,🇸🇳 Senegal,0.541158,99.0,Lado B / Semifinal 102
20,93,r16,07/06/2026 14:00,Portugal,Spain,🇵🇹 Portugal,🇪🇸 Spain,Spain,🇪🇸 Spain,0.717654,98.0,Lado A / Semifinal 101
21,94,r16,07/06/2026 17:00,United States,Belgium,🇺🇸 United States,🇧🇪 Belgium,Belgium,🇧🇪 Belgium,0.890181,98.0,Lado A / Semifinal 101
22,95,r16,07/07/2026 12:00,Argentina,Australia,🇦🇷 Argentina,🇦🇺 Australia,Argentina,🇦🇷 Argentina,0.941222,100.0,Lado B / Semifinal 102
23,96,r16,07/07/2026 13:00,Senegal,Colombia,🇸🇳 Senegal,🇨🇴 Colombia,Colombia,🇨🇴 Colombia,0.578057,100.0,Lado B / Semifinal 102
24,97,qf,07/09/2026 16:00,France,Netherlands,🇫🇷 France,🇳🇱 Netherlands,France,🇫🇷 France,0.594313,101.0,Lado A / Semifinal 101
25,98,qf,07/10/2026 12:00,Spain,Belgium,🇪🇸 Spain,🇧🇪 Belgium,Spain,🇪🇸 Spain,0.918058,101.0,Lado A / Semifinal 101
26,99,qf,07/11/2026 17:00,Brazil,Senegal,🇧🇷 Brazil,🇸🇳 Senegal,Brazil,🇧🇷 Brazil,0.780356,102.0,Lado B / Semifinal 102
27,100,qf,07/11/2026 20:00,Argentina,Colombia,🇦🇷 Argentina,🇨🇴 Colombia,Argentina,🇦🇷 Argentina,0.855770,102.0,Lado B / Semifinal 102
28,101,sf,07/14/2026 14:00,France,Spain,🇫🇷 France,🇪🇸 Spain,Spain,🇪🇸 Spain,0.573649,104.0,Lado A / Semifinal 101
29,102,sf,07/15/2026 15:00,Brazil,Argentina,🇧🇷 Brazil,🇦🇷 Argentina,Argentina,🇦🇷 Argentina,0.684554,104.0,Lado B / Semifinal 102
30,104,final,07/19/2026 15:00,Spain,Argentina,🇪🇸 Spain,🇦🇷 Argentina,Spain,🇪🇸 Spain,0.500745,NaN,Final

In [2]:
import pandas as pd
import numpy as np
import re
import unicodedata
from pathlib import Path

print("Corrigiendo coherencia del campeón proyectado con favorito global...")

UNCERTAINTY_MARGIN = 0.02
# 0.02 = margen de 2 puntos porcentuales.
# Si un partido está entre 48% y 52%, gana el equipo con mayor probabilidad global de campeón.

# =========================
# 1. Buscar archivos
# =========================

search_roots = [
    Path.cwd(),
    Path.cwd().parent,
    Path.cwd().parent.parent
]

bracket_files = []
ranking_files = []
simulator_files = []
tournament_files = []

for root in search_roots:
    if root.exists():
        bracket_files.extend(list(root.rglob("official_tournament_bracket_normalized.xlsx")))
        ranking_files.extend(list(root.rglob("world_cup_live_power_ranking.xlsx")))
        simulator_files.extend(list(root.rglob("world_cup_match_simulator.xlsx")))
        tournament_files.extend(list(root.rglob("world_cup_tournament_simulation_real_bracket.xlsx")))

bracket_files = list(dict.fromkeys(bracket_files))
ranking_files = list(dict.fromkeys(ranking_files))
simulator_files = list(dict.fromkeys(simulator_files))
tournament_files = list(dict.fromkeys(tournament_files))

if not bracket_files:
    raise FileNotFoundError("No encontré official_tournament_bracket_normalized.xlsx")

if not ranking_files:
    raise FileNotFoundError("No encontré world_cup_live_power_ranking.xlsx")

if not simulator_files:
    raise FileNotFoundError("No encontré world_cup_match_simulator.xlsx")

if not tournament_files:
    raise FileNotFoundError("No encontré world_cup_tournament_simulation_real_bracket.xlsx")

bracket_file = bracket_files[0]
ranking_file = ranking_files[0]
simulator_file = simulator_files[0]
tournament_file = tournament_files[0]

print("Bracket real:", bracket_file)
print("Ranking:", ranking_file)
print("Simulador:", simulator_file)
print("Simulación real:", tournament_file)

# =========================
# 2. Cargar datos
# =========================

bracket_sheets = pd.read_excel(bracket_file, sheet_name=None)
tournament_sheets = pd.read_excel(tournament_file, sheet_name=None)

knockout = bracket_sheets["knockout_bracket"].copy()
ranking = pd.read_excel(ranking_file)
simulator = pd.read_excel(simulator_file)

round_probabilities = tournament_sheets["round_probabilities_real"].copy()

# =========================
# 3. Normalización de nombres
# =========================

name_aliases = {
    "Curaçao": "Curacao",
    "Curacao": "Curacao",
    "Czechia": "Czech Republic",
    "Czech Republic": "Czech Republic",
    "Democratic Republic of the Congo": "Congo",
    "DR Congo": "Congo",
    "Congo DR": "Congo",
    "Congo": "Congo",
    "United States": "United States",
    "USA": "United States",
}

def normalize_text(value):
    if pd.isna(value):
        return ""
    value = str(value).strip()
    value = unicodedata.normalize("NFKD", value)
    value = "".join([c for c in value if not unicodedata.combining(c)])
    return value

def canonical_team(value):
    if pd.isna(value):
        return ""
    
    value = str(value).strip()
    
    if value in name_aliases:
        return name_aliases[value]
    
    value_clean = normalize_text(value)
    
    for original, mapped in name_aliases.items():
        if normalize_text(original).lower() == value_clean.lower():
            return mapped
    
    return value

for col in ["team", "team_display"]:
    if col in round_probabilities.columns:
        round_probabilities[col] = round_probabilities[col].apply(
            lambda x: x if col == "team_display" else canonical_team(x)
        )

ranking["team"] = ranking["team"].apply(canonical_team)

if "team_display" not in ranking.columns:
    ranking["team_display"] = ranking["team"]

ranking = ranking.drop_duplicates(subset=["team"]).reset_index(drop=True)

team_info = ranking.set_index("team").to_dict("index")

def team_display(team):
    team = canonical_team(team)
    return team_info.get(team, {}).get("team_display", team)

def team_confederation(team):
    team = canonical_team(team)
    return team_info.get(team, {}).get("confederation", "")

def team_ranking(team):
    team = canonical_team(team)
    return team_info.get(team, {}).get("ranking", 99)

def team_power(team):
    team = canonical_team(team)
    return float(team_info.get(team, {}).get("power_score_live", 0.50))

def team_rating(team):
    team = canonical_team(team)
    return float(team_info.get(team, {}).get("rating", 1500))

# =========================
# 4. Favorito global del modelo
# =========================

round_probabilities["team"] = round_probabilities["team"].apply(canonical_team)

round_probabilities = round_probabilities.sort_values(
    "champion_probability",
    ascending=False
).reset_index(drop=True)

global_favorite_row = round_probabilities.iloc[0]
global_favorite = global_favorite_row["team"]

champion_prob_map = dict(
    zip(
        round_probabilities["team"],
        round_probabilities["champion_probability"]
    )
)

print("Favorito global del modelo:", team_display(global_favorite))
print("Probabilidad global:", round(global_favorite_row["champion_probability"] * 100, 2), "%")

# =========================
# 5. Aplicar terceros ya resueltos
# =========================

if "third_place_assignments" in tournament_sheets:
    third_place_assignments = tournament_sheets["third_place_assignments"].copy()
    
    if not third_place_assignments.empty:
        for _, row in third_place_assignments.iterrows():
            match_id = int(row["match_id"])
            side = str(row["side"])
            selected_team = canonical_team(row["selected_team"])
            
            team_col = f"team_{side}"
            status_col = f"team_{side}_status"
            
            mask = knockout["match_id"] == match_id
            
            if team_col in knockout.columns:
                knockout.loc[mask, team_col] = selected_team
            
            if status_col in knockout.columns:
                knockout.loc[mask, status_col] = "resolved_third_place_model"

# =========================
# 6. Probabilidades de cruce directo
# =========================

for col in ["team_a", "team_b"]:
    simulator[col] = simulator[col].apply(canonical_team)

for col in ["win_a_probability", "draw_probability", "win_b_probability"]:
    simulator[col] = pd.to_numeric(simulator[col], errors="coerce")
    if simulator[col].max() > 1:
        simulator[col] = simulator[col] / 100

pair_probs = (
    simulator[
        ["team_a", "team_b", "win_a_probability", "draw_probability", "win_b_probability"]
    ]
    .drop_duplicates(subset=["team_a", "team_b"])
    .copy()
)

advance_prob = {}

for _, row in pair_probs.iterrows():
    a = row["team_a"]
    b = row["team_b"]
    win_a = float(row["win_a_probability"])
    draw = float(row["draw_probability"])
    win_b = float(row["win_b_probability"])
    
    advance_prob[(a, b)] = win_a + draw * 0.5
    advance_prob[(b, a)] = win_b + draw * 0.5

def fallback_probability(team_a, team_b):
    power_diff = team_power(team_a) - team_power(team_b)
    rating_diff = (team_rating(team_a) - team_rating(team_b)) / 600
    
    x = power_diff * 2.5 + rating_diff
    p = 1 / (1 + np.exp(-x))
    
    return float(np.clip(p, 0.05, 0.95))

def get_advance_probability(team_a, team_b):
    team_a = canonical_team(team_a)
    team_b = canonical_team(team_b)
    
    if team_a == team_b:
        return 1.0
    
    if (team_a, team_b) in advance_prob:
        return advance_prob[(team_a, team_b)]
    
    return fallback_probability(team_a, team_b)

# =========================
# 7. Resolver participantes
# =========================

def resolve_participant(label, winners, losers=None):
    label = str(label)
    
    label_clean = label.lower()
    
    if "winner" in label_clean and "match" in label_clean:
        nums = re.findall(r"\d+", label)
        if nums:
            match_id = int(nums[-1])
            return winners.get(match_id, "")
    
    if "loser" in label_clean and "match" in label_clean and losers is not None:
        nums = re.findall(r"\d+", label)
        if nums:
            match_id = int(nums[-1])
            return losers.get(match_id, "")
    
    return canonical_team(label)

# =========================
# 8. Regla de ganador coherente
# =========================

def projected_winner_consistent(team_a, team_b):
    team_a = canonical_team(team_a)
    team_b = canonical_team(team_b)
    
    p_a = get_advance_probability(team_a, team_b)
    p_b = 1 - p_a
    
    prob_a_global = champion_prob_map.get(team_a, 0)
    prob_b_global = champion_prob_map.get(team_b, 0)
    
    # Si el cruce está muy parejo, usamos probabilidad global de campeón como desempate.
    if abs(p_a - 0.5) <= UNCERTAINTY_MARGIN:
        if prob_a_global >= prob_b_global:
            return team_a, p_a, "global_favorite_tiebreak"
        else:
            return team_b, p_b, "global_favorite_tiebreak"
    
    # Si no está parejo, gana el que tiene mayor probabilidad directa del cruce.
    if p_a >= p_b:
        return team_a, p_a, "head_to_head_probability"
    else:
        return team_b, p_b, "head_to_head_probability"

# =========================
# 9. Recalcular bracket proyectado
# =========================

knockout["match_id"] = pd.to_numeric(knockout["match_id"], errors="coerce").astype(int)

round_sequence = ["r32", "r16", "qf", "sf", "final"]

matches_to_project = knockout[
    knockout["round_type"].isin(round_sequence)
].copy()

matches_to_project = matches_to_project.sort_values("match_id")

projected_rows = []
projected_winners = {}
projected_losers = {}

for _, row in matches_to_project.iterrows():
    match_id = int(row["match_id"])
    round_type = row["round_type"]
    
    team_a = resolve_participant(row["team_a"], projected_winners, projected_losers)
    team_b = resolve_participant(row["team_b"], projected_winners, projected_losers)
    
    real_winner = canonical_team(row.get("real_winner", ""))
    finished = bool(row.get("finished", False))
    
    if finished and real_winner and real_winner != "Draw":
        winner = real_winner
        winner_probability = 1.0
        decision_rule = "real_result"
    else:
        winner, winner_probability, decision_rule = projected_winner_consistent(team_a, team_b)
    
    loser = team_b if winner == team_a else team_a
    
    projected_winners[match_id] = winner
    projected_losers[match_id] = loser
    
    projected_rows.append({
        "match_id": match_id,
        "round_type": round_type,
        "date": row.get("date", ""),
        "team_a": team_a,
        "team_b": team_b,
        "team_a_display": team_display(team_a),
        "team_b_display": team_display(team_b),
        "projected_winner": winner,
        "projected_winner_display": team_display(winner),
        "winner_probability": winner_probability,
        "decision_rule": decision_rule,
        "next_match_id": row.get("next_match_id", ""),
        "bracket_side": row.get("bracket_side", "")
    })

projected_bracket = pd.DataFrame(projected_rows)

# =========================
# 10. Actualizar key cards
# =========================

final_projected = projected_bracket[projected_bracket["round_type"] == "final"].iloc[0]
champion_projected = final_projected["projected_winner"]

champion_probs = round_probabilities[
    round_probabilities["team"] == champion_projected
].iloc[0]

sf_projected = projected_bracket[projected_bracket["round_type"] == "sf"].copy()

round_progress_champion = pd.DataFrame([
    {
        "round": "16avos",
        "probability": champion_probs["round_32_probability"]
    },
    {
        "round": "Octavos",
        "probability": champion_probs["round_16_probability"]
    },
    {
        "round": "Cuartos",
        "probability": champion_probs["quarterfinal_probability"]
    },
    {
        "round": "Semifinales",
        "probability": champion_probs["semifinal_probability"]
    },
    {
        "round": "Final",
        "probability": champion_probs["final_probability"]
    },
    {
        "round": "Campeón",
        "probability": champion_probs["champion_probability"]
    }
])

previous_key_cards = tournament_sheets["key_cards_real"]

key_cards = pd.DataFrame([{
    "champion": champion_projected,
    "champion_display": team_display(champion_projected),
    "champion_probability": champion_probs["champion_probability"],
    "final_probability": champion_probs["final_probability"],
    "semifinal_probability": champion_probs["semifinal_probability"],
    "teams_simulated": previous_key_cards["teams_simulated"].iloc[0],
    "simulations": previous_key_cards["simulations"].iloc[0],
    "final_team_a_display": final_projected["team_a_display"],
    "final_team_b_display": final_projected["team_b_display"],
    "final_winner_display": final_projected["projected_winner_display"],
    "final_match_probability": final_projected["winner_probability"],
    "final_decision_rule": final_projected["decision_rule"],
    "semi_1_team_a_display": sf_projected.iloc[0]["team_a_display"],
    "semi_1_team_b_display": sf_projected.iloc[0]["team_b_display"],
    "semi_1_winner_display": sf_projected.iloc[0]["projected_winner_display"],
    "semi_1_probability": sf_projected.iloc[0]["winner_probability"],
    "semi_1_decision_rule": sf_projected.iloc[0]["decision_rule"],
    "semi_2_team_a_display": sf_projected.iloc[1]["team_a_display"],
    "semi_2_team_b_display": sf_projected.iloc[1]["team_b_display"],
    "semi_2_winner_display": sf_projected.iloc[1]["projected_winner_display"],
    "semi_2_probability": sf_projected.iloc[1]["winner_probability"],
    "semi_2_decision_rule": sf_projected.iloc[1]["decision_rule"],
}])

model_decision_notes = pd.DataFrame([
    {
        "rule": "global_favorite_tiebreak",
        "description": "Si un cruce está dentro de un margen de 48%-52%, el modelo desempata usando la probabilidad global de campeón."
    },
    {
        "rule": "head_to_head_probability",
        "description": "Si el cruce no está parejo, gana el equipo con mayor probabilidad directa en ese partido."
    },
    {
        "rule": "real_result",
        "description": "Si el partido ya terminó, se respeta el resultado real."
    }
])

# =========================
# 11. Guardar archivo actualizado
# =========================

tournament_sheets["key_cards_real"] = key_cards
tournament_sheets["projected_bracket_real"] = projected_bracket
tournament_sheets["round_progress_champion_real"] = round_progress_champion
tournament_sheets["model_decision_notes"] = model_decision_notes

with pd.ExcelWriter(tournament_file, engine="openpyxl") as writer:
    for sheet_name, df in tournament_sheets.items():
        df.to_excel(writer, sheet_name=sheet_name, index=False)

print("Archivo actualizado correctamente:")
print(tournament_file)

print("\nCampeón proyectado coherente:")
display(key_cards)

print("\nFinal proyectada:")
display(
    projected_bracket[
        projected_bracket["round_type"] == "final"
    ][
        [
            "team_a_display",
            "team_b_display",
            "projected_winner_display",
            "winner_probability",
            "decision_rule"
        ]
    ]
)

print("\nSemifinales proyectadas:")
display(
    projected_bracket[
        projected_bracket["round_type"] == "sf"
    ][
        [
            "team_a_display",
            "team_b_display",
            "projected_winner_display",
            "winner_probability",
            "decision_rule"
        ]
    ]
)

Corrigiendo coherencia del campeón proyectado con favorito global...
Bracket real: c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Notebooks\official_tournament_bracket_normalized.xlsx
Ranking: c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Notebooks\world_cup_live_power_ranking.xlsx
Simulador: c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Notebooks\world_cup_match_simulator.xlsx
Simulación real: c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Notebooks\world_cup_tournament_simulation_real_bracket.xlsx
Favorito global del modelo: 🇦🇷 Argentina
Probabilidad global: 36.7 %
Archivo actualizado correctamente:
c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Notebooks\world_cup_tournament_simulation_real_bracket.xlsx

Campeón proyectado coherente:

c:\Users\Samsung\AppData\Local\Programs\Python\Python314\Lib\site-packages\openpyxl\workbook\child.py:99: UserWarning: Title is more than 31 characters. Some applications may not be able to read the file
  warnings.warn("Title is more than 31 characters. Some applications may not be able to read the file")

,champion,champion_display,champion_probability,final_probability,semifinal_probability,teams_simulated,simulations,final_team_a_display,final_team_b_display,final_winner_display,...,semi_1_team_a_display,semi_1_team_b_display,semi_1_winner_display,semi_1_probability,semi_1_decision_rule,semi_2_team_a_display,semi_2_team_b_display,semi_2_winner_display,semi_2_probability,semi_2_decision_rule
0,Argentina,🇦🇷 Argentina,0.36704,0.63288,0.79612,48,25000,🇪🇸 Spain,🇦🇷 Argentina,🇦🇷 Argentina,...,🇫🇷 France,🇪🇸 Spain,🇪🇸 Spain,0.573649,head_to_head_probability,🇧🇷 Brazil,🇦🇷 Argentina,🇦🇷 Argentina,0.684554,head_to_head_probability

Final proyectada:

,team_a_display,team_b_display,projected_winner_display,winner_probability,decision_rule
30,🇪🇸 Spain,🇦🇷 Argentina,🇦🇷 Argentina,0.499255,global_favorite_tiebreak

Semifinales proyectadas:

,team_a_display,team_b_display,projected_winner_display,winner_probability,decision_rule
28,🇫🇷 France,🇪🇸 Spain,🇪🇸 Spain,0.573649,head_to_head_probability
29,🇧🇷 Brazil,🇦🇷 Argentina,🇦🇷 Argentina,0.684554,head_to_head_probability

In [3]:
import pandas as pd
import numpy as np
import re
import unicodedata
from pathlib import Path

print("Corrigiendo bracket real y regenerando simulación completa...")

N_SIMULATIONS = 25000
RANDOM_SEED = 42
UNCERTAINTY_MARGIN = 0.02

rng = np.random.default_rng(RANDOM_SEED)

# =========================
# 1. Buscar archivos
# =========================

search_roots = [
    Path.cwd(),
    Path.cwd().parent,
    Path.cwd().parent.parent
]

bracket_files = []
ranking_files = []
simulator_files = []
tournament_files = []

for root in search_roots:
    if root.exists():
        bracket_files.extend(list(root.rglob("official_tournament_bracket_normalized.xlsx")))
        ranking_files.extend(list(root.rglob("world_cup_live_power_ranking.xlsx")))
        simulator_files.extend(list(root.rglob("world_cup_match_simulator.xlsx")))
        tournament_files.extend(list(root.rglob("world_cup_tournament_simulation_real_bracket.xlsx")))

bracket_files = list(dict.fromkeys(bracket_files))
ranking_files = list(dict.fromkeys(ranking_files))
simulator_files = list(dict.fromkeys(simulator_files))
tournament_files = list(dict.fromkeys(tournament_files))

if not bracket_files:
    raise FileNotFoundError("No encontré official_tournament_bracket_normalized.xlsx")

if not ranking_files:
    raise FileNotFoundError("No encontré world_cup_live_power_ranking.xlsx")

if not simulator_files:
    raise FileNotFoundError("No encontré world_cup_match_simulator.xlsx")

if not tournament_files:
    raise FileNotFoundError("No encontré world_cup_tournament_simulation_real_bracket.xlsx")

bracket_file = bracket_files[0]
ranking_file = ranking_files[0]
simulator_file = simulator_files[0]
tournament_file = tournament_files[0]

print("Bracket real:", bracket_file)
print("Ranking:", ranking_file)
print("Simulador:", simulator_file)
print("Simulación:", tournament_file)

# =========================
# 2. Cargar datos
# =========================

bracket_sheets = pd.read_excel(bracket_file, sheet_name=None)
tournament_sheets = pd.read_excel(tournament_file, sheet_name=None)

knockout = bracket_sheets["knockout_bracket"].copy()
official_games = bracket_sheets["official_games"].copy()

ranking = pd.read_excel(ranking_file)
simulator = pd.read_excel(simulator_file)

# =========================
# 3. Normalizar nombres
# =========================

name_aliases = {
    "Curaçao": "Curacao",
    "Curacao": "Curacao",
    "Czechia": "Czech Republic",
    "Czech Republic": "Czech Republic",
    "Democratic Republic of the Congo": "Congo",
    "DR Congo": "Congo",
    "Congo DR": "Congo",
    "Congo": "Congo",
    "United States": "United States",
    "USA": "United States",
}

def normalize_text(value):
    if pd.isna(value):
        return ""
    value = str(value).strip()
    value = unicodedata.normalize("NFKD", value)
    value = "".join([c for c in value if not unicodedata.combining(c)])
    return value

def canonical_team(value):
    if pd.isna(value):
        return ""
    
    value = str(value).strip()
    
    if value in name_aliases:
        return name_aliases[value]
    
    value_clean = normalize_text(value)
    
    for original, mapped in name_aliases.items():
        if normalize_text(original).lower() == value_clean.lower():
            return mapped
    
    return value

ranking["team"] = ranking["team"].apply(canonical_team)

if "team_display" not in ranking.columns:
    ranking["team_display"] = ranking["team"]

ranking = ranking.drop_duplicates(subset=["team"]).reset_index(drop=True)

team_info = ranking.set_index("team").to_dict("index")

def team_display(team):
    team = canonical_team(team)
    return team_info.get(team, {}).get("team_display", team)

def team_confederation(team):
    team = canonical_team(team)
    return team_info.get(team, {}).get("confederation", "")

def team_ranking(team):
    team = canonical_team(team)
    return team_info.get(team, {}).get("ranking", 99)

def team_power(team):
    team = canonical_team(team)
    return float(team_info.get(team, {}).get("power_score_live", 0.50))

def team_rating(team):
    team = canonical_team(team)
    return float(team_info.get(team, {}).get("rating", 1500))

# =========================
# 4. Corregir 16avos reales
# =========================

r32_real_matches = {
    73: ("South Africa", "Canada"),
    74: ("Germany", "Paraguay"),
    75: ("Netherlands", "Morocco"),
    76: ("Brazil", "Japan"),
    77: ("France", "Sweden"),
    78: ("Ivory Coast", "Norway"),
    79: ("Mexico", "Ecuador"),
    80: ("England", "Congo"),
    81: ("United States", "Bosnia and Herzegovina"),
    82: ("Belgium", "Senegal"),
    83: ("Portugal", "Croatia"),
    84: ("Spain", "Austria"),
    85: ("Switzerland", "Algeria"),
    86: ("Argentina", "Cape Verde"),
    87: ("Colombia", "Ghana"),
    88: ("Australia", "Egypt"),
}

for match_id, (team_a, team_b) in r32_real_matches.items():
    mask_ko = knockout["match_id"] == match_id
    mask_all = official_games["match_id"] == match_id
    
    knockout.loc[mask_ko, "team_a"] = canonical_team(team_a)
    knockout.loc[mask_ko, "team_b"] = canonical_team(team_b)
    knockout.loc[mask_ko, "team_a_status"] = "official_team"
    knockout.loc[mask_ko, "team_b_status"] = "official_team"
    
    official_games.loc[mask_all, "team_a"] = canonical_team(team_a)
    official_games.loc[mask_all, "team_b"] = canonical_team(team_b)
    official_games.loc[mask_all, "team_a_status"] = "official_team"
    official_games.loc[mask_all, "team_b_status"] = "official_team"

print("16avos corregidos:")
display(
    knockout[
        knockout["round_type"] == "r32"
    ][
        ["match_id", "round_type", "team_a", "team_b", "next_match_id", "bracket_side"]
    ]
)

# =========================
# 5. Probabilidades de cruce directo
# =========================

for col in ["team_a", "team_b"]:
    simulator[col] = simulator[col].apply(canonical_team)

for col in ["win_a_probability", "draw_probability", "win_b_probability"]:
    simulator[col] = pd.to_numeric(simulator[col], errors="coerce")
    if simulator[col].max() > 1:
        simulator[col] = simulator[col] / 100

pair_probs = (
    simulator[
        ["team_a", "team_b", "win_a_probability", "draw_probability", "win_b_probability"]
    ]
    .drop_duplicates(subset=["team_a", "team_b"])
    .copy()
)

advance_prob = {}

for _, row in pair_probs.iterrows():
    a = canonical_team(row["team_a"])
    b = canonical_team(row["team_b"])
    win_a = float(row["win_a_probability"])
    draw = float(row["draw_probability"])
    win_b = float(row["win_b_probability"])
    
    advance_prob[(a, b)] = win_a + draw * 0.5
    advance_prob[(b, a)] = win_b + draw * 0.5

def fallback_probability(team_a, team_b):
    power_diff = team_power(team_a) - team_power(team_b)
    rating_diff = (team_rating(team_a) - team_rating(team_b)) / 600
    
    x = power_diff * 2.5 + rating_diff
    p = 1 / (1 + np.exp(-x))
    
    return float(np.clip(p, 0.05, 0.95))

def get_advance_probability(team_a, team_b):
    team_a = canonical_team(team_a)
    team_b = canonical_team(team_b)
    
    if team_a == team_b:
        return 1.0
    
    if (team_a, team_b) in advance_prob:
        return advance_prob[(team_a, team_b)]
    
    return fallback_probability(team_a, team_b)

# =========================
# 6. Resolver participantes
# =========================

def resolve_participant(label, winners, losers=None):
    label = str(label)
    label_clean = label.lower()
    
    if "winner" in label_clean and "match" in label_clean:
        nums = re.findall(r"\d+", label)
        if nums:
            match_id = int(nums[-1])
            return winners.get(match_id, "")
    
    if "loser" in label_clean and "match" in label_clean and losers is not None:
        nums = re.findall(r"\d+", label)
        if nums:
            match_id = int(nums[-1])
            return losers.get(match_id, "")
    
    return canonical_team(label)

def play_match(team_a, team_b):
    p_a = get_advance_probability(team_a, team_b)
    return team_a if rng.random() < p_a else team_b

# =========================
# 7. Simulación Monte Carlo sobre bracket corregido
# =========================

round_sequence = ["r32", "r16", "qf", "sf", "final"]

matches_to_simulate = knockout[
    knockout["round_type"].isin(round_sequence)
].copy()

matches_to_simulate["match_id"] = pd.to_numeric(
    matches_to_simulate["match_id"],
    errors="coerce"
).astype(int)

matches_to_simulate = matches_to_simulate.sort_values("match_id")

teams_in_model = sorted(ranking["team"].unique())

round_counts = {
    team: {
        "round_32_probability": 0,
        "round_16_probability": 0,
        "quarterfinal_probability": 0,
        "semifinal_probability": 0,
        "final_probability": 0,
        "champion_probability": 0
    }
    for team in teams_in_model
}

print("Iniciando simulaciones...")

for sim in range(N_SIMULATIONS):
    if sim % 5000 == 0:
        print("Simulación:", sim)
    
    winners = {}
    losers = {}
    
    # Contar participantes reales de 16avos
    r32_matches = matches_to_simulate[
        matches_to_simulate["round_type"] == "r32"
    ]
    
    for _, row in r32_matches.iterrows():
        team_a = canonical_team(row["team_a"])
        team_b = canonical_team(row["team_b"])
        
        if team_a in round_counts:
            round_counts[team_a]["round_32_probability"] += 1
        
        if team_b in round_counts:
            round_counts[team_b]["round_32_probability"] += 1
    
    for _, row in matches_to_simulate.iterrows():
        match_id = int(row["match_id"])
        round_type = row["round_type"]
        
        team_a = resolve_participant(row["team_a"], winners, losers)
        team_b = resolve_participant(row["team_b"], winners, losers)
        
        real_winner = canonical_team(row.get("real_winner", ""))
        finished = bool(row.get("finished", False))
        
        if finished and real_winner and real_winner != "Draw":
            winner = real_winner
        else:
            winner = play_match(team_a, team_b)
        
        loser = team_b if winner == team_a else team_a
        
        winners[match_id] = winner
        losers[match_id] = loser
        
        if round_type == "r32":
            if winner in round_counts:
                round_counts[winner]["round_16_probability"] += 1
        
        elif round_type == "r16":
            if winner in round_counts:
                round_counts[winner]["quarterfinal_probability"] += 1
        
        elif round_type == "qf":
            if winner in round_counts:
                round_counts[winner]["semifinal_probability"] += 1
        
        elif round_type == "sf":
            if winner in round_counts:
                round_counts[winner]["final_probability"] += 1
        
        elif round_type == "final":
            if winner in round_counts:
                round_counts[winner]["champion_probability"] += 1

print("Simulaciones terminadas.")

# =========================
# 8. Tablas de probabilidades
# =========================

round_probabilities = []

for team, counts in round_counts.items():
    row = {
        "team": team,
        "team_display": team_display(team),
        "confederation": team_confederation(team),
        "ranking": team_ranking(team),
        "power_score_live": team_power(team),
        "rating": team_rating(team)
    }
    
    for col, value in counts.items():
        row[col] = value / N_SIMULATIONS
    
    round_probabilities.append(row)

round_probabilities = pd.DataFrame(round_probabilities)

round_probabilities = round_probabilities.sort_values(
    "champion_probability",
    ascending=False
).reset_index(drop=True)

top_candidates = round_probabilities.head(8).copy()

confederation_probabilities = (
    round_probabilities
    .groupby("confederation", as_index=False)["champion_probability"]
    .sum()
    .sort_values("champion_probability", ascending=False)
)

surprises = (
    round_probabilities[
        round_probabilities["ranking"] > 8
    ]
    .sort_values("champion_probability", ascending=False)
    .head(5)
    .copy()
)

champion_prob_map = dict(
    zip(
        round_probabilities["team"],
        round_probabilities["champion_probability"]
    )
)

# =========================
# 9. Bracket proyectado coherente
# =========================

def projected_winner_consistent(team_a, team_b):
    team_a = canonical_team(team_a)
    team_b = canonical_team(team_b)
    
    p_a = get_advance_probability(team_a, team_b)
    p_b = 1 - p_a
    
    prob_a_global = champion_prob_map.get(team_a, 0)
    prob_b_global = champion_prob_map.get(team_b, 0)
    
    # Si está dentro de 48%-52%, desempata la probabilidad global de campeón
    if abs(p_a - 0.5) <= UNCERTAINTY_MARGIN:
        if prob_a_global >= prob_b_global:
            return team_a, p_a, "global_favorite_tiebreak"
        else:
            return team_b, p_b, "global_favorite_tiebreak"
    
    if p_a >= p_b:
        return team_a, p_a, "head_to_head_probability"
    else:
        return team_b, p_b, "head_to_head_probability"

projected_rows = []
projected_winners = {}
projected_losers = {}

for _, row in matches_to_simulate.iterrows():
    match_id = int(row["match_id"])
    round_type = row["round_type"]
    
    team_a = resolve_participant(row["team_a"], projected_winners, projected_losers)
    team_b = resolve_participant(row["team_b"], projected_winners, projected_losers)
    
    real_winner = canonical_team(row.get("real_winner", ""))
    finished = bool(row.get("finished", False))
    
    if finished and real_winner and real_winner != "Draw":
        winner = real_winner
        winner_probability = 1.0
        decision_rule = "real_result"
    else:
        winner, winner_probability, decision_rule = projected_winner_consistent(team_a, team_b)
    
    loser = team_b if winner == team_a else team_a
    
    projected_winners[match_id] = winner
    projected_losers[match_id] = loser
    
    projected_rows.append({
        "match_id": match_id,
        "round_type": round_type,
        "date": row.get("date", ""),
        "team_a": team_a,
        "team_b": team_b,
        "team_a_display": team_display(team_a),
        "team_b_display": team_display(team_b),
        "projected_winner": winner,
        "projected_winner_display": team_display(winner),
        "winner_probability": winner_probability,
        "decision_rule": decision_rule,
        "next_match_id": row.get("next_match_id", ""),
        "bracket_side": row.get("bracket_side", "")
    })

projected_bracket = pd.DataFrame(projected_rows)

# =========================
# 10. Key cards
# =========================

final_projected = projected_bracket[
    projected_bracket["round_type"] == "final"
].iloc[0]

champion_projected = final_projected["projected_winner"]

champion_probs = round_probabilities[
    round_probabilities["team"] == champion_projected
].iloc[0]

sf_projected = projected_bracket[
    projected_bracket["round_type"] == "sf"
].copy()

round_progress_champion = pd.DataFrame([
    {"round": "16avos", "probability": champion_probs["round_32_probability"]},
    {"round": "Octavos", "probability": champion_probs["round_16_probability"]},
    {"round": "Cuartos", "probability": champion_probs["quarterfinal_probability"]},
    {"round": "Semifinales", "probability": champion_probs["semifinal_probability"]},
    {"round": "Final", "probability": champion_probs["final_probability"]},
    {"round": "Campeón", "probability": champion_probs["champion_probability"]},
])

key_cards = pd.DataFrame([{
    "champion": champion_projected,
    "champion_display": team_display(champion_projected),
    "champion_probability": champion_probs["champion_probability"],
    "final_probability": champion_probs["final_probability"],
    "semifinal_probability": champion_probs["semifinal_probability"],
    "teams_simulated": len(teams_in_model),
    "simulations": N_SIMULATIONS,
    "final_team_a_display": final_projected["team_a_display"],
    "final_team_b_display": final_projected["team_b_display"],
    "final_winner_display": final_projected["projected_winner_display"],
    "final_match_probability": final_projected["winner_probability"],
    "final_decision_rule": final_projected["decision_rule"],
    "semi_1_team_a_display": sf_projected.iloc[0]["team_a_display"],
    "semi_1_team_b_display": sf_projected.iloc[0]["team_b_display"],
    "semi_1_winner_display": sf_projected.iloc[0]["projected_winner_display"],
    "semi_1_probability": sf_projected.iloc[0]["winner_probability"],
    "semi_1_decision_rule": sf_projected.iloc[0]["decision_rule"],
    "semi_2_team_a_display": sf_projected.iloc[1]["team_a_display"],
    "semi_2_team_b_display": sf_projected.iloc[1]["team_b_display"],
    "semi_2_winner_display": sf_projected.iloc[1]["projected_winner_display"],
    "semi_2_probability": sf_projected.iloc[1]["winner_probability"],
    "semi_2_decision_rule": sf_projected.iloc[1]["decision_rule"],
}])

model_decision_notes = pd.DataFrame([
    {
        "rule": "global_favorite_tiebreak",
        "description": "Si un cruce está dentro de 48%-52%, el modelo desempata usando la probabilidad global de campeón."
    },
    {
        "rule": "head_to_head_probability",
        "description": "Si el cruce no está parejo, gana el equipo con mayor probabilidad directa."
    },
    {
        "rule": "real_result",
        "description": "Si el partido ya terminó, se respeta el resultado real."
    }
])

# =========================
# 11. Guardar archivos
# =========================

# Actualizar archivo de bracket normalizado
bracket_sheets["official_games"] = official_games
bracket_sheets["knockout_bracket"] = knockout

with pd.ExcelWriter(bracket_file, engine="openpyxl") as writer:
    for sheet_name, df in bracket_sheets.items():
        df.to_excel(writer, sheet_name=sheet_name, index=False)

# Actualizar archivo de simulación
tournament_sheets["key_cards_real"] = key_cards
tournament_sheets["round_probabilities_real"] = round_probabilities
tournament_sheets["top_candidates_real"] = top_candidates
tournament_sheets["round_progress_champion_real"] = round_progress_champion
tournament_sheets["confederation_probabilities_real"] = confederation_probabilities
tournament_sheets["surprises_real"] = surprises
tournament_sheets["projected_bracket_real"] = projected_bracket
tournament_sheets["model_decision_notes"] = model_decision_notes

with pd.ExcelWriter(tournament_file, engine="openpyxl") as writer:
    for sheet_name, df in tournament_sheets.items():
        df.to_excel(writer, sheet_name=sheet_name, index=False)

print("Archivos actualizados correctamente.")
print("Bracket:", bracket_file)
print("Simulación:", tournament_file)

print("\nCampeón proyectado:")
display(key_cards)

print("\nTop candidatos:")
display(
    top_candidates[
        ["team_display", "champion_probability", "final_probability", "semifinal_probability"]
    ]
)

print("\nBracket proyectado corregido:")
display(
    projected_bracket[
        ["match_id", "round_type", "team_a_display", "team_b_display", "projected_winner_display", "winner_probability", "decision_rule", "next_match_id", "bracket_side"]
    ]
)

Corrigiendo bracket real y regenerando simulación completa...
Bracket real: c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Notebooks\official_tournament_bracket_normalized.xlsx
Ranking: c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Notebooks\world_cup_live_power_ranking.xlsx
Simulador: c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Notebooks\world_cup_match_simulator.xlsx
Simulación: c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Notebooks\world_cup_tournament_simulation_real_bracket.xlsx
16avos corregidos:

,match_id,round_type,team_a,team_b,next_match_id,bracket_side
0,73,r32,South Africa,Canada,90.0,Lado A / Semifinal 101
1,74,r32,Germany,Paraguay,89.0,Lado A / Semifinal 101
2,75,r32,Netherlands,Morocco,90.0,Lado A / Semifinal 101
3,76,r32,Brazil,Japan,91.0,Lado B / Semifinal 102
4,77,r32,France,Sweden,89.0,Lado A / Semifinal 101
5,78,r32,Ivory Coast,Norway,91.0,Lado B / Semifinal 102
6,79,r32,Mexico,Ecuador,92.0,Lado B / Semifinal 102
7,80,r32,England,Congo,92.0,Lado B / Semifinal 102
8,81,r32,United States,Bosnia and Herzegovina,94.0,Lado A / Semifinal 101
9,82,r32,Belgium,Senegal,94.0,Lado A / Semifinal 101
10,83,r32,Portugal,Croatia,93.0,Lado A / Semifinal 101
11,84,r32,Spain,Austria,93.0,Lado A / Semifinal 101
12,85,r32,Switzerland,Algeria,96.0,Lado B / Semifinal 102
13,86,r32,Argentina,Cape Verde,95.0,Lado B / Semifinal 102
14,87,r32,Colombia,Ghana,96.0,Lado B / Semifinal 102
15,88,r32,Australia,Egypt,95.0,Lado B / Semifinal 102

Iniciando simulaciones...
Simulación: 0
Simulación: 5000
Simulación: 10000
Simulación: 15000
Simulación: 20000
Simulaciones terminadas.
Archivos actualizados correctamente.
Bracket: c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Notebooks\official_tournament_bracket_normalized.xlsx
Simulación: c:\Users\Samsung\OneDrive\Desktop\World Cup 2026\Notebooks\world_cup_tournament_simulation_real_bracket.xlsx

Campeón proyectado:

c:\Users\Samsung\AppData\Local\Programs\Python\Python314\Lib\site-packages\openpyxl\workbook\child.py:99: UserWarning: Title is more than 31 characters. Some applications may not be able to read the file
  warnings.warn("Title is more than 31 characters. Some applications may not be able to read the file")

,champion,champion_display,champion_probability,final_probability,semifinal_probability,teams_simulated,simulations,final_team_a_display,final_team_b_display,final_winner_display,...,semi_1_team_a_display,semi_1_team_b_display,semi_1_winner_display,semi_1_probability,semi_1_decision_rule,semi_2_team_a_display,semi_2_team_b_display,semi_2_winner_display,semi_2_probability,semi_2_decision_rule
0,Argentina,🇦🇷 Argentina,0.33036,0.56392,0.79932,48,25000,🇪🇸 Spain,🇦🇷 Argentina,🇦🇷 Argentina,...,🇫🇷 France,🇪🇸 Spain,🇪🇸 Spain,0.573649,head_to_head_probability,🏴 England,🇦🇷 Argentina,🇦🇷 Argentina,0.657427,head_to_head_probability

Top candidatos:

,team_display,champion_probability,final_probability,semifinal_probability
0,🇦🇷 Argentina,0.33036,0.56392,0.79932
1,🇪🇸 Spain,0.25108,0.41960,0.65680
2,🇫🇷 France,0.16184,0.30992,0.57580
3,🏴 England,0.09512,0.22444,0.51604
4,🇳🇱 Netherlands,0.05884,0.13716,0.30320
5,🇧🇷 Brazil,0.04292,0.10800,0.27060
6,🇵🇹 Portugal,0.02800,0.07364,0.17568
7,🇯🇵 Japan,0.00844,0.02960,0.10312

Bracket proyectado corregido:

,match_id,round_type,team_a_display,team_b_display,projected_winner_display,winner_probability,decision_rule,next_match_id,bracket_side
0,73,r32,🇿🇦 South Africa,🇨🇦 Canada,🇨🇦 Canada,0.819221,head_to_head_probability,90.0,Lado A / Semifinal 101
1,74,r32,🇩🇪 Germany,🇵🇾 Paraguay,🇩🇪 Germany,0.693839,head_to_head_probability,89.0,Lado A / Semifinal 101
2,75,r32,🇳🇱 Netherlands,🇲🇦 Morocco,🇳🇱 Netherlands,0.711783,head_to_head_probability,90.0,Lado A / Semifinal 101
3,76,r32,🇧🇷 Brazil,🇯🇵 Japan,🇧🇷 Brazil,0.635251,head_to_head_probability,91.0,Lado B / Semifinal 102
4,77,r32,🇫🇷 France,🇸🇪 Sweden,🇫🇷 France,0.951204,head_to_head_probability,89.0,Lado A / Semifinal 101
5,78,r32,🇨🇮 Ivory Coast,🇳🇴 Norway,🇳🇴 Norway,0.881221,head_to_head_probability,91.0,Lado B / Semifinal 102
6,79,r32,🇲🇽 Mexico,🇪🇨 Ecuador,🇪🇨 Ecuador,0.613025,head_to_head_probability,92.0,Lado B / Semifinal 102
7,80,r32,🏴 England,🇨🇩 Congo,🏴 England,0.959842,head_to_head_probability,92.0,Lado B / Semifinal 102
8,81,r32,🇺🇸 United States,🇧🇦 Bosnia and Herzegovina,🇺🇸 United States,0.574631,head_to_head_probability,94.0,Lado A / Semifinal 101
9,82,r32,🇧🇪 Belgium,🇸🇳 Senegal,🇸🇳 Senegal,0.549142,head_to_head_probability,94.0,Lado A / Semifinal 101
10,83,r32,🇵🇹 Portugal,🇭🇷 Croatia,🇵🇹 Portugal,0.723123,head_to_head_probability,93.0,Lado A / Semifinal 101
11,84,r32,🇪🇸 Spain,🇦🇹 Austria,🇪🇸 Spain,0.939592,head_to_head_probability,93.0,Lado A / Semifinal 101
12,85,r32,🇨🇭 Switzerland,🇩🇿 Algeria,🇨🇭 Switzerland,0.646632,head_to_head_probability,96.0,Lado B / Semifinal 102
13,86,r32,🇦🇷 Argentina,🇨🇻 Cape Verde,🇦🇷 Argentina,0.959842,head_to_head_probability,95.0,Lado B / Semifinal 102
14,87,r32,🇨🇴 Colombia,🇬🇭 Ghana,🇨🇴 Colombia,0.940755,head_to_head_probability,96.0,Lado B / Semifinal 102
15,88,r32,🇦🇺 Australia,🇪🇬 Egypt,🇦🇺 Australia,0.711906,head_to_head_probability,95.0,Lado B / Semifinal 102
16,89,r16,🇩🇪 Germany,🇫🇷 France,🇫🇷 France,0.862534,head_to_head_probability,97.0,Lado A / Semifinal 101
17,90,r16,🇨🇦 Canada,🇳🇱 Netherlands,🇳🇱 Netherlands,0.891417,head_to_head_probability,97.0,Lado A / Semifinal 101
18,91,r16,🇧🇷 Brazil,🇳🇴 Norway,🇧🇷 Brazil,0.770238,head_to_head_probability,99.0,Lado B / Semifinal 102
19,92,r16,🇪🇨 Ecuador,🏴 England,🏴 England,0.830110,head_to_head_probability,99.0,Lado B / Semifinal 102
20,93,r16,🇵🇹 Portugal,🇪🇸 Spain,🇪🇸 Spain,0.717654,head_to_head_probability,98.0,Lado A / Semifinal 101
21,94,r16,🇺🇸 United States,🇸🇳 Senegal,🇸🇳 Senegal,0.912180,head_to_head_probability,98.0,Lado A / Semifinal 101
22,95,r16,🇦🇷 Argentina,🇦🇺 Australia,🇦🇷 Argentina,0.941222,head_to_head_probability,100.0,Lado B / Semifinal 102
23,96,r16,🇨🇭 Switzerland,🇨🇴 Colombia,🇨🇴 Colombia,0.613139,head_to_head_probability,100.0,Lado B / Semifinal 102
24,97,qf,🇫🇷 France,🇳🇱 Netherlands,🇫🇷 France,0.594313,head_to_head_probability,101.0,Lado A / Semifinal 101
25,98,qf,🇪🇸 Spain,🇸🇳 Senegal,🇪🇸 Spain,0.897117,head_to_head_probability,101.0,Lado A / Semifinal 101
26,99,qf,🇧🇷 Brazil,🏴 England,🏴 England,0.529723,head_to_head_probability,102.0,Lado B / Semifinal 102
27,100,qf,🇦🇷 Argentina,🇨🇴 Colombia,🇦🇷 Argentina,0.855770,head_to_head_probability,102.0,Lado B / Semifinal 102
28,101,sf,🇫🇷 France,🇪🇸 Spain,🇪🇸 Spain,0.573649,head_to_head_probability,104.0,Lado A / Semifinal 101
29,102,sf,🏴 England,🇦🇷 Argentina,🇦🇷 Argentina,0.657427,head_to_head_probability,104.0,Lado B / Semifinal 102
30,104,final,🇪🇸 Spain,🇦🇷 Argentina,🇦🇷 Argentina,0.499255,global_favorite_tiebreak,NaN,Final